- .github/workflows/pr-naming.yml
- .github/workflows/release.yml
Add a release pipeline to publish repositories to nuget.org
> feat: add release pipeline

- .github/workflows/ci.yml
- Testably.Abstractions.sln
Activates code coverage in SonarCloud
> feat: enable code coverage analysis

- Source/Testably.Abstractions.Testing/FileSystemMock.Directory.cs
- Source/Testably.Abstractions.Testing/FileSystemMock.IInMemoryFileSystem.cs
- Source/Testably.Abstractions.Testing/Internal/InMemoryFileSystem.cs
- Source/Testably.Abstractions/Models/DirectoryInfoWrapper.cs
- Tests/Testably.Abstractions.Tests/FileSystemDirectoryInfoTests.cs
- Tests/Testably.Abstractions.Tests/FileSystemDirectoryTests.cs
Also fix implementation of Delete with recursive parameter for IFileSystem.Directory
> feat: implement `IFileSystem.Directory.EnumerateDirectories` overloads

- .github/workflows/pr-naming.yml
- Docs/Examples/Examples.csproj
- Source/Directory.Build.props
- Tests/Directory.Build.props
Update
- `Microsoft.NET.Test.Sdk` to 17.3.1
- `xunit` to 2.4.2
- `xunit.runner.visualstudio` to 2.4.5
- `Nullable` to 1.3.1
> chore: update nuget packages

- .github/workflows/ci.yml
- Source/Testably.Abstractions.Testing/RandomProvider.cs
- Source/Testably.Abstractions/RandomSystem.RandomFactory.cs
- Tests/Testably.Abstractions.Tests/RandomSystemRandomTests.cs
- Tests/Testably.Abstractions.Tests/Testing/RandomProviderTests.cs
Make Random.New thread-safe on .NET Framework
Include version for SonarCloud scan
> fix: Thread-Safe issue with random system on .NET Framework

- .github/workflows/ci.yml
- .github/workflows/stryker.yml
- Testably.Abstractions.sln
- Tests/stryker-config-extensions.json
- Tests/stryker-config.json
Analyze the quality of the unit test suite using [.NET Stryker](https://stryker-mutator.io/docs/stryker-net/introduction/).
> feat: enable .NET Stryker

- .github/workflows/stryker.yml
- README.md
- Tests/stryker-config-extensions.json
- Tests/stryker-config.json
Add a badge with the result from Stryker on README.md
> feat: add stryker badge

- README.md
Add Getting Started section
Add information about RandomSystem
Add links to nuget packages
> doc: improve and update README.md

- Source/Testably.Abstractions.Testing/FileSystemMock.Directory.cs
- Source/Testably.Abstractions.Testing/FileSystemMock.DirectoryInfoFactory.cs
- Source/Testably.Abstractions.Testing/FileSystemMock.FileInfoFactory.cs
- Source/Testably.Abstractions.Testing/FileSystemMock.InMemoryFileSystem.cs
- Source/Testably.Abstractions.Testing/Internal/PathHelper.cs
- Source/Testably.Abstractions.Testing/RandomProvider.cs
- Source/Testably.Abstractions/FileSystem.DirectoryInfoFactory.cs
- Source/Testably.Abstractions/FileSystem.FileInfoFactory.cs
- Source/Testably.Abstractions/IFileSystem.IDirectoryInfoFactory.cs
- Source/Testably.Abstractions/IFileSystem.IFileInfoFactory.cs
- Source/Testably.Abstractions/IRandomSystem.Random.cs
- Source/Testably.Abstractions/RandomSystem.RandomFactory.cs
- Tests/Testably.Abstractions.Tests/DependencyInjectionTests.cs
- Tests/Testably.Abstractions.Tests/FileSystemDirectoryInfoTests.cs
- Tests/Testably.Abstractions.Tests/FileSystemDirectoryTests.EnumerateFiles.cs
- Tests/Testably.Abstractions.Tests/FileSystemFileInfoTests.cs
- Tests/Testably.Abstractions.Tests/RandomSystemGuidTests.cs
- Tests/Testably.Abstractions.Tests/RandomSystemTests.cs
- Tests/Testably.Abstractions.Tests/TestHelpers/ParityCheckHelper.cs
- Tests/Testably.Abstractions.Tests/Testably.Abstractions.Tests.csproj
- Tests/Testably.Abstractions.Tests/Testing/FileSystemInitializerTests.cs
- Tests/Testably.Abstractions.Tests/Testing/RandomProviderTests.cs
- Tests/stryker-config-testing.json
Allows to wrap a `FileInfo` or `DirectoryInfo` into the interface types used within the `IFileSystem`.
> feat: wrap file info and directory info

- Source/Testably.Abstractions.Testing/FileSystemMock.Directory.cs
- Source/Testably.Abstractions.Testing/FileSystemMock.DirectoryInfo.cs
- Source/Testably.Abstractions.Testing/FileSystemMock.File.cs
- Source/Testably.Abstractions.Testing/FileSystemMock.FileInfo.cs
- Source/Testably.Abstractions.Testing/FileSystemMock.FileStream.cs
- Source/Testably.Abstractions.Testing/FileSystemMock.FileSystemInfo.cs
- Source/Testably.Abstractions.Testing/FileSystemMock.IInMemoryFileSystem.cs
- Source/Testably.Abstractions.Testing/FileSystemMock.InMemoryFileSystem.cs
- Source/Testably.Abstractions.Testing/Internal/ExceptionFactory.cs
- Source/Testably.Abstractions.Testing/Internal/PathHelper.cs
- Source/Testably.Abstractions.Testing/TimeSystemMock.Task.cs
- Source/Testably.Abstractions.Testing/TimeSystemMock.Thread.cs
- Tests/Testably.Abstractions.Tests/FileSystemDirectoryInfoTests.Enumerate.cs
- Tests/Testably.Abstractions.Tests/FileSystemDirectoryTests.Create.cs
- Tests/Testably.Abstractions.Tests/FileSystemDirectoryTests.EnumerateDirectories.cs
Centralize all common exceptions into one `ExceptionFactory` class.
> refactor: centralize exception generation

- Feature.Flags.props
- Source/Testably.Abstractions.Extensions/Timer/Timer.cs
- Source/Testably.Abstractions.Testing/FileSystemMock.Directory.cs
- Source/Testably.Abstractions.Testing/FileSystemMock.IInMemoryFileSystem.cs
- Source/Testably.Abstractions.Testing/FileSystemMock.InMemoryFileSystem.cs
- Source/Testably.Abstractions.Testing/FileSystemMock.cs
- Source/Testably.Abstractions.Testing/TimeProvider.cs
- Source/Testably.Abstractions.Testing/TimeSystemMock.cs
- Tests/Testably.Abstractions.Extensions.Tests/TimeSystemExtensionsTimerTests.cs
- Tests/Testably.Abstractions.Tests/FileSystemDirectoryTests.Directories.cs
- Tests/Testably.Abstractions.Tests/FileSystemDirectoryTests.FileSystemEntries.cs
- Tests/Testably.Abstractions.Tests/FileSystemDirectoryTests.Files.cs
- Tests/Testably.Abstractions.Tests/FileSystemDirectoryTests.Times.cs
- Tests/Testably.Abstractions.Tests/FileSystemDirectoryTests.cs
- Tests/Testably.Abstractions.Tests/TestHelpers/Attributes/RealFileSystemTestAttribute.cs
- Tests/Testably.Abstractions.Tests/Testing/TimeProviderTests.cs
Test edge cases in the Timer class
Implement GetFiles, GetDirectories and GetFileSystemEntries
Implement Times functionality on Mocked Directory
> feat: implement additional functionality on `FileSystemMock.Directory`

- .github/workflows/stryker.yml
- Tests/Testably.Abstractions.Extensions.Tests/TimeSystemExtensionsTimerTests.cs
- Tests/stryker-config-extensions.json
- Tests/stryker-config-testing.json
- Tests/stryker-config.json
Change config and build pipeline to execute "Dashboard" reporter only in build pipeline
> feat: allow Stryker to be run locally

- .github/workflows/stryker.yml
- Tests/Testably.Abstractions.Tests/TestHelpers/Attributes/RealFileSystemTestAttribute.cs
- Tests/Testably.Abstractions.Tests/TestHelpers/Framework/TestablyTestFrameworkDiscoverer.cs
Run Stryker on Windows as it is only detecting a small subset of tests under ubuntu
> fix: Stryker not detecting all tests under ubuntu

- Source/Testably.Abstractions.Testing/FileSystemMock.FileInfoMock.cs
- Source/Testably.Abstractions.Testing/FileSystemMock.FileMock.cs
- Source/Testably.Abstractions.Testing/Internal/EncryptionHelper.cs
- Tests/Testably.Abstractions.Tests/FileSystemFileInfoTests.EncryptDecrypt.cs
- Tests/Testably.Abstractions.Tests/FileSystemFileInfoTests.cs
- Tests/Testably.Abstractions.Tests/Testing/NotificationTests.cs
Implement Encryption/Decryption of files
> feat: implement Encryption and Decryption

- Source/Testably.Abstractions.Testing/FileSystemMock.DirectoryMock.cs
- Source/Testably.Abstractions.Testing/FileSystemMock.FileMock.cs
- Tests/Testably.Abstractions.Tests/FileSystemFileTests.Times.cs
Implement Get/Set CreationTime, LastAccessTime and LastWriteTime on the FileMock
> feat: implement times for filemock

- Source/Testably.Abstractions.Testing/FileSystemMock.INotificationHandler.cs
- Source/Testably.Abstractions.Testing/Notification.cs
- Source/Testably.Abstractions.Testing/TimeSystemMock.CallbackHandler.cs
- Source/Testably.Abstractions.Testing/TimeSystemMock.ICallbackHandler.cs
- Tests/Testably.Abstractions.Tests/FileSystemMockNotificationTests.cs
- Tests/Testably.Abstractions.Tests/Testing/NotificationTests.cs
> fix: simplify notification tests

- Source/Testably.Abstractions.Testing/FileSystemInitializer.Initializer.cs
- Source/Testably.Abstractions.Testing/FileSystemMock.DirectoryInfoMock.cs
- Source/Testably.Abstractions.Testing/FileSystemMock.DirectoryMock.cs
- Source/Testably.Abstractions.Testing/FileSystemMock.DriveInfoMock.cs
- Source/Testably.Abstractions.Testing/FileSystemMock.FileInfoMock.cs
- Source/Testably.Abstractions.Testing/FileSystemMock.FileMock.cs
- Source/Testably.Abstractions.Testing/FileSystemMock.FileSystemInfoMock.cs
- Source/Testably.Abstractions.Testing/Internal/ExceptionFactory.cs
- Source/Testably.Abstractions.Testing/Internal/FileSystemExtensions.cs
- Source/Testably.Abstractions.Testing/Storage/IStorage.cs
- Source/Testably.Abstractions.Testing/Storage/InMemoryLocation.cs
- Source/Testably.Abstractions.Testing/Storage/InMemoryStorage.cs
- Testably.Abstractions.v3.ncrunchsolution
- Tests/Testably.Abstractions.Tests/FileSystemDirectoryInfoTests.MoveTo.cs
- Tests/Testably.Abstractions.Tests/FileSystemDirectoryTests.Move.cs
- Tests/Testably.Abstractions.Tests/FileSystemFileInfoTests.MoveTo.cs
- Tests/Testably.Abstractions.Tests/FileSystemFileTests.Move.cs
- Tests/Testably.Abstractions.Tests/Mock/MockFileSystem.FileTests.cs
Implement the following methods:
`IFile.Move`, `IFileInfo.MoveTo`, `IDirectory.Move` , `IDirectoryInfo.MoveTo`
> feat: implement move functionality

- Source/Testably.Abstractions.Testing/FileSystemMock.FileInfoMock.cs
- Source/Testably.Abstractions.Testing/FileSystemMock.FileMock.cs
- Tests/Testably.Abstractions.Tests/FileSystemFileInfoTests.AppendText.cs
- Tests/Testably.Abstractions.Tests/FileSystemFileInfoTests.CreateText.cs
- Tests/Testably.Abstractions.Tests/FileSystemFileInfoTests.OpenText.cs
- Tests/Testably.Abstractions.Tests/FileSystemFileTests.AppendText.cs
- Tests/Testably.Abstractions.Tests/FileSystemFileTests.CreateText.cs
- Tests/Testably.Abstractions.Tests/FileSystemFileTests.OpenText.cs
Implement `AppendText` , `CreateText` and `OpenText` methods on `IFile` and `IFileInfo`.
> feat: add streamwriter methods

- Source/Testably.Abstractions.Testing/FileSystemMock.DirectoryInfoMock.cs
- Source/Testably.Abstractions.Testing/FileSystemMock.FileInfoMock.cs
- Source/Testably.Abstractions.Testing/FileSystemMock.FileMock.cs
- Source/Testably.Abstractions.Testing/Storage/IStorage.cs
- Source/Testably.Abstractions.Testing/Storage/InMemoryStorage.cs
- Tests/Testably.Abstractions.Tests/FileSystemFileInfoTests.CopyTo.cs
- Tests/Testably.Abstractions.Tests/FileSystemFileTests.Copy.cs
Implement `IFile.Copy` and `IFileInfo`.`CopyTo` methods.
> feat: implement `Copy` and `CopyTo` for file system

- Source/Testably.Abstractions.Testing/FileSystemMock.FileInfoMock.cs
- Source/Testably.Abstractions.Testing/FileSystemMock.FileMock.cs
- Source/Testably.Abstractions.Testing/FileSystemMock.FileSystemInfoMock.cs
- Source/Testably.Abstractions.Testing/Internal/ExceptionFactory.cs
- Source/Testably.Abstractions.Testing/Storage/IStorage.cs
- Source/Testably.Abstractions.Testing/Storage/IStorageContainer.cs
- Source/Testably.Abstractions.Testing/Storage/InMemoryContainer.cs
- Source/Testably.Abstractions.Testing/Storage/InMemoryStorage.cs
- Source/Testably.Abstractions.Testing/Storage/NullContainer.cs
- Tests/Testably.Abstractions.Tests/FileSystemDirectoryInfoTests.MoveTo.cs
- Tests/Testably.Abstractions.Tests/FileSystemDirectoryInfoTests.cs
- Tests/Testably.Abstractions.Tests/FileSystemDirectoryTests.Move.cs
- Tests/Testably.Abstractions.Tests/FileSystemFileInfoTests.CopyTo.cs
- Tests/Testably.Abstractions.Tests/FileSystemFileInfoTests.MoveTo.cs
- Tests/Testably.Abstractions.Tests/FileSystemFileInfoTests.Replace.cs
- Tests/Testably.Abstractions.Tests/FileSystemFileTests.Copy.cs
- Tests/Testably.Abstractions.Tests/FileSystemFileTests.Replace.cs
- Tests/Testably.Abstractions.Tests/Mock/MockFileSystem.FileTests.cs
Implement `IFile.Replace` and `IFileInfo.Replace` methods.
> feat: implement `Replace` for file system

- Source/Testably.Abstractions.Testing/FileSystemMock.FileStreamMock.cs
- Source/Testably.Abstractions.Testing/FileSystemMock.FileSystemInfoMock.cs
- Source/Testably.Abstractions.Testing/FileSystemMock.FileSystemWatcherFactoryMock.cs
- Source/Testably.Abstractions.Testing/Notification.cs
- Source/Testably.Abstractions.Testing/RandomSystemMock.IRandomProvider.cs
- Source/Testably.Abstractions.Testing/RandomSystemMock.RandomProviderMock.cs
- Source/Testably.Abstractions.Testing/TimeSystemMock.TaskMock.cs
- Source/Testably.Abstractions.Testing/TimeSystemMock.ThreadMock.cs
- Source/Testably.Abstractions/FileSystem.DriveInfoFactory.cs
- Tests/Testably.Abstractions.Testing.Tests/NotificationTests.cs
- Tests/Testably.Abstractions.Testing.Tests/RandomProviderTests.cs
- Tests/Testably.Abstractions.Testing.Tests/TimeSystemMockTests.cs
- Tests/Testably.Abstractions.Tests/FileSystemDriveInfoFactoryTests.cs
- Tests/Testably.Abstractions.Tests/FileSystemFileStreamFactoryTests.cs
- Tests/Testably.Abstractions.Tests/FileSystemFileStreamTests.Options.cs
- Tests/Testably.Abstractions.Tests/FileSystemFileStreamTests.cs
- Tests/Testably.Abstractions.Tests/FileSystemFileSystemWatcherFactoryTests.cs
- Tests/Testably.Abstractions.Tests/Real/RealFileSystem.FileSystemWatcherFactoryTests.cs
Fix (some) issues detected by Stryker: added missing tests or simplified the implementation :-)
- Improve code coverage for `DriveInfoFactory`
- Improve code coverage for `TimeSystemMock`
- Improve code coverage for `RandomProvider`
- Improve code coverage for `Notification`
- Improve code coverage for `FileStream`
- Simplify `FileSystemInfoMock`
- Enable wrapping of `FileSystemWatcher`
> refactor: improve coverage and simplify code

- Source/Testably.Abstractions.Testing/FileSystemMock.DriveInfoFactoryMock.cs
- Source/Testably.Abstractions.Testing/FileSystemMock.DriveInfoMock.cs
- Source/Testably.Abstractions.Testing/FileSystemMock.cs
- Source/Testably.Abstractions.Testing/FileSystemMockExtensions.cs
- Source/Testably.Abstractions.Testing/Internal/PathHelper.cs
- Source/Testably.Abstractions.Testing/Storage/InMemoryStorage.cs
- Tests/Testably.Abstractions.Testing.Tests/FileSystemMockTests.cs
- Tests/Testably.Abstractions.Tests/FileSystemFileTests.ReadAllText.cs
- Tests/Testably.Abstractions.Tests/Mock/MockFileSystem.FileTests.cs
Consider the edge cases from #54 and implement support for UNC paths
> feat: support UNC paths

- Source/Testably.Abstractions.Testing/FileSystemMock.ChangeHandler.cs
- Source/Testably.Abstractions.Testing/FileSystemMock.FileSystemWatcherMock.cs
- Source/Testably.Abstractions.Testing/FileSystemMock.IInterceptionHandler.cs
- Source/Testably.Abstractions.Testing/FileSystemMock.INotificationHandler.cs
- Source/Testably.Abstractions.Testing/FileSystemMockExtensions.IInterceptionHandler.cs
- Source/Testably.Abstractions.Testing/FileSystemMockExtensions.INotificationHandler.cs
- Tests/Testably.Abstractions.Testing.Tests/FileSystemInitializer/DirectoryCleanerTests.cs
- Tests/Testably.Abstractions.Testing.Tests/FileSystemMock/InterceptionHandlerExtensionsTests.cs
- Tests/Testably.Abstractions.Testing.Tests/FileSystemMock/InterceptionHandlerTests.cs
- Tests/Testably.Abstractions.Testing.Tests/FileSystemMock/NotificationHandlerExtensionsTests.cs
- Tests/Testably.Abstractions.Testing.Tests/FileSystemMock/NotificationHandlerTests.cs
- Tests/Testably.Abstractions.Testing.Tests/Storage/InMemoryStorageTests.cs
> feat: add extension methods for `IInterceptionHandler`

- Source/Testably.Abstractions.Testing/FileSystemMock.FileInfoMock.cs
- Source/Testably.Abstractions.Testing/FileSystemMock.FileMock.cs
- Source/Testably.Abstractions.Testing/FileSystemMock.FileStreamMock.cs
- Source/Testably.Abstractions.Testing/Internal/Execute.cs
- Source/Testably.Abstractions.Testing/TimeSystemMock.TimeProviderMock.cs
- Tests/Testably.Abstractions.Testing.Tests/FileSystemMock/FileSystemMockTests.cs
- Tests/Testably.Abstractions.Testing.Tests/TimeSystemMock/TimeSystemMockTests.cs
- Tests/Testably.Abstractions.Tests/FileSystem/FileStream/FileSystemFileStreamTests.cs
- Tests/Testably.Abstractions.Tests/FileSystem/FileSystemWatcher/FileSystemFileSystemWatcherTests.IncludeSubdirectories.cs
- Tests/Testably.Abstractions.Tests/FileSystem/FileSystemWatcher/FileSystemFileSystemWatcherTests.WaitForChanged.cs
- Tests/Testably.Abstractions.Tests/FileSystem/FileSystemWatcher/FileSystemFileSystemWatcherTests.cs
- Tests/Testably.Abstractions.Tests/TestHelpers/Test.cs
> refactor: improve coverage

- Examples/Examples.sln
- Examples/README.md
- Examples/ThreadAwareTimeProvider/ThreadAwareTimeProvider.Tests/ThreadAwareTimeProviderTests.cs
- Examples/ThreadAwareTimeProvider/ThreadAwareTimeProvider/ThreadAwareTimeProvider.cs
- Examples/ThreadAwareTimeProvider/ThreadAwareTimeProvider/ThreadAwareTimeProvider.csproj
- Examples/Timer/TimerExample/SynchronizationTimer.cs
- Examples/ZipFile/README.md
- Examples/ZipFile/ZipFile.Tests/ZipFile.Tests.csproj
- Examples/ZipFile/ZipFile.Tests/ZipFileHelperTests.cs
- Examples/ZipFile/ZipFile/ZipFile.csproj
- Examples/ZipFile/ZipFile/ZipFileHelper.cs
Add an example how to use `System.IO.Compression` in combination with `IFileSystem`
- to compress a directory into a zip file
- to extract a zip file into a directory
> doc: add example for Zip File

- .github/workflows/build.yml
- .github/workflows/release.yml
- Testably.Abstractions.sln
Create a release branch for release handling and protect releases with an environment.
*This is only a part of the intended changes...*
> feat: change release handling (1)

- .github/workflows/ci.yml
- .github/workflows/release.yml
- README.md
Create a release branch for release handling and protect releases with an environment.
This is a part of the intended changes started in #126
> feat: change release handling (2)

- .github/workflows/release.yml
Fixes that the release should create a corresponding tag!
> feat: change release handling (3)

- .github/workflows/release.yml
Fix image in README.md
Use correct version for SonarCloud
Add Cleanup step
> feat: change release handling (4)

- Source/Testably.Abstractions.Testing/FileSystemMock.FileInfoMock.cs
- Source/Testably.Abstractions.Testing/Internal/EncryptionHelper.cs
- Source/Testably.Abstractions.Testing/Internal/Execute.cs
- Source/Testably.Abstractions.Testing/Storage/InMemoryContainer.cs
- Source/Testably.Abstractions.Testing/Storage/InMemoryLocation.cs
- Source/Testably.Abstractions.Testing/Storage/InMemoryStorage.cs
- Tests/Testably.Abstractions.Testing.Tests/FileSystemMock/FileMockTests.cs
- Tests/Testably.Abstractions.Testing.Tests/Storage/InMemoryContainerTests.cs
- Tests/Testably.Abstractions.Testing.Tests/Storage/InMemoryStorageTests.cs
- Tests/Testably.Abstractions.Tests/FileSystem/Directory/FileSystemDirectoryTests.AdjustTimes.cs
- Tests/Testably.Abstractions.Tests/FileSystem/FileInfo/FileSystemFileInfoTests.cs
- Tests/Testably.Abstractions.Tests/FileSystem/FileStream/FileSystemFileStreamTests.cs
- Tests/stryker-config-testing.json
Improve test coverage for `EncryptionHelper`, `FileInfoMock`, `FileMock`, `FileStreamMock`, `InMemoryLocation`, `InMemoryContainer`, `InMemoryStorage`.
> refactor: refactor: improve test coverage

- Feature.Flags.props
- Source/Directory.Build.props
- Source/Testably.Abstractions.Interface/FileSystemStream.cs
- Source/Testably.Abstractions.Interface/IFileSystem.IDirectoryInfo.cs
- Source/Testably.Abstractions.Interface/IFileSystem.IDriveInfo.cs
- Source/Testably.Abstractions.Interface/IFileSystem.IFile.cs
- Source/Testably.Abstractions.Interface/IFileSystem.IFileInfo.cs
- Source/Testably.Abstractions.Interface/Polyfills/SupportedOsPlatformAttribute.cs
- Source/Testably.Abstractions.Testing/FileSystemMock.DirectoryInfoMock.cs
- Source/Testably.Abstractions.Testing/FileSystemMock.DriveInfoMock.cs
- Source/Testably.Abstractions.Testing/FileSystemMock.FileInfoMock.cs
- Source/Testably.Abstractions.Testing/FileSystemMock.FileMock.cs
- Source/Testably.Abstractions.Testing/FileSystemMock.FileStreamMock.cs
- Source/Testably.Abstractions.Testing/Storage/IStorageContainer.cs
- Source/Testably.Abstractions.Testing/Storage/InMemoryContainer.cs
- Source/Testably.Abstractions.Testing/Storage/NullContainer.cs
- Source/Testably.Abstractions/FileSystem.DirectoryInfoWrapper.cs
- Source/Testably.Abstractions/FileSystem.DriveInfoWrapper.cs
- Source/Testably.Abstractions/FileSystem.FileInfoWrapper.cs
- Source/Testably.Abstractions/FileSystem.FileStreamWrapper.cs
- Source/Testably.Abstractions/FileSystem.FileWrapper.cs
- Tests/Directory.Build.props
- Tests/Testably.Abstractions.Parity.Tests/Net472ParityTests.cs
- Tests/Testably.Abstractions.Testing.Tests/FileSystemMock/DirectoryInfoMockTest.cs
- Tests/Testably.Abstractions.Testing.Tests/FileSystemMock/FileInfoMockTests.cs
- Tests/Testably.Abstractions.Testing.Tests/FileSystemMock/FileStreamMockTests.cs
- Tests/Testably.Abstractions.Testing.Tests/TestHelpers/LockableContainer.cs
- Tests/Testably.Abstractions.Tests/FileSystem/FileInfo/FileSystemFileInfoTests.EncryptDecrypt.cs
> feat: support ACL features

- CONTRIBUTING.md
> doc: add contributor guide

- CODE_OF_CONDUCT.md
> doc: code of conduct

- Feature.Flags.props
- Source/Testably.Abstractions.Compression/FileSystemExtensions.cs
- Source/Testably.Abstractions.Compression/IZipArchive.cs
- Source/Testably.Abstractions.Compression/IZipArchiveEntry.cs
- Source/Testably.Abstractions.Compression/IZipArchiveFactory.cs
- Source/Testably.Abstractions.Compression/IZipFile.cs
- Source/Testably.Abstractions.Compression/Internal/Execute.cs
- Source/Testably.Abstractions.Compression/Internal/ZipUtilities.cs
- Source/Testably.Abstractions.Compression/ZipArchiveEntryWrapper.cs
- Source/Testably.Abstractions.Compression/ZipArchiveFactory.cs
- Source/Testably.Abstractions.Compression/ZipArchiveWrapper.cs
- Source/Testably.Abstractions.Compression/ZipFileWrapper.cs
- Tests/Testably.Abstractions.Compression.Tests/TestHelpers/Test.cs
- Tests/Testably.Abstractions.Compression.Tests/ZipArchive/MockFileSystemTests.cs
- Tests/Testably.Abstractions.Compression.Tests/ZipArchive/RealFileSystemTests.cs
- Tests/Testably.Abstractions.Compression.Tests/ZipArchive/ZipArchiveTests.cs
- Tests/Testably.Abstractions.Compression.Tests/ZipArchiveEntry/MockFileSystemTests.cs
- Tests/Testably.Abstractions.Compression.Tests/ZipArchiveEntry/RealFileSystemTests.cs
- Tests/Testably.Abstractions.Compression.Tests/ZipArchiveEntry/ZipArchiveEntryTests.cs
- Tests/Testably.Abstractions.Compression.Tests/ZipFile/MockFileSystemTests.cs
- Tests/Testably.Abstractions.Compression.Tests/ZipFile/RealFileSystemTests.cs
- Tests/Testably.Abstractions.Compression.Tests/ZipFile/ZipFileTests.cs
- Tests/Testably.Abstractions.Compression.Tests/ZipFileTests.cs
Add interfaces for `IZipArchive` and `IZipArchiveEntry` to the Compression library.
> feat(compression): add interfaces to "Compression" library

- .github/stryker/Stryker.Config.AccessControl.json
- .github/stryker/Stryker.Config.Compression.json
- .github/stryker/Stryker.Config.Testing.json
- .github/stryker/Stryker.Config.json
- .github/workflows/ci.yml
- .github/workflows/pr.yml
- .github/workflows/stryker.yml
> feat: add Stryker analysis to pull requests

- .github/workflows/ci.yml
- Tests/Testably.Abstractions.Testing.Tests/Notification/NotificationTests.cs
Include a step in the CI pipeline that adds a comment to remind about the Stryker Dashboard to the pull request.
- #149
> feat: add comment from Stryker-CI-Build

- .github/workflows/ci-qa.yml
- .github/workflows/ci.yml
- Testably.Abstractions.sln
Remove Dashboard reporter from Stryker
> fix: enable CI builds from forked repositories

- Tests/Testably.Abstractions.Testing.Tests/FileSystem/FileSystemWatcherFactoryMockTests.cs
- Tests/Testably.Abstractions.Testing.Tests/Testably.Abstractions.Testing.Tests.csproj
- Tests/Testably.Abstractions.Tests.SourceGenerator/ClassToGenerate.cs
- Tests/Testably.Abstractions.Tests.SourceGenerator/TestGenerator.cs
- Tests/Testably.Abstractions.Tests/FileSystem/FileInfo/Tests.cs
- Tests/Testably.Abstractions.Tests/FileSystem/FileSystemWatcher/Tests.cs
Some tests were inadvertently removed in #174. Re-enable them.
Also fix code issue found by sonarcloud.
> fix: re-enable missing tests

- Source/Testably.Abstractions.Testing/FileSystem/FileStreamFactoryMock.cs
- Source/Testably.Abstractions.Testing/MockFileSystem.cs
- Tests/Testably.Abstractions.Testing.Tests/MockFileSystemTests.cs
- Tests/Testably.Abstractions.Testing.Tests/NotificationTests.cs
- Tests/Testably.Abstractions.Testing.Tests/TimeProviderTests.cs
Also add tests for `Notification` and `TimeProvider`
> refactor: add tests for SafeFileHandle in MockFileSystem

- .github/workflows/release.yml
> fix: readme adaptions in release build

- Examples/AccessControlLists/AccessControlLists.Tests/AccessControlListTests.cs
- Examples/AccessControlLists/AccessControlLists.Tests/AccessControlLists.Tests.csproj
- Examples/AccessControlLists/AccessControlLists/AccessControlLists.csproj
- Examples/AccessControlLists/AccessControlLists/CustomAccessControlStrategy.cs
- Examples/AccessControlLists/README.md
- Examples/Directory.Build.props
- Examples/Examples.sln
- Examples/README.md
- Examples/SafeFileHandle/README.md
- Examples/SafeFileHandle/SafeFileHandle.Tests/SafeFileHandle.Tests.csproj
- Examples/SafeFileHandle/SafeFileHandle.Tests/SafeFileHandleTests.cs
- Examples/SafeFileHandle/SafeFileHandle/CustomSafeFileHandleStrategy.cs
- Examples/SafeFileHandle/SafeFileHandle/SafeFileHandle.csproj
- Examples/SafeFileHandle/SafeFileHandle/UnmanagedFileLoader.cs
- Source/Testably.Abstractions.Testing/FileSystem/NullAccessControlStrategy.cs
- Source/Testably.Abstractions.Testing/MockFileSystem.cs
- Source/Testably.Abstractions.Testing/Storage/InMemoryContainer.cs
- Source/Testably.Abstractions.Testing/Storage/InMemoryStorage.cs
- Tests/Testably.Abstractions.Testing.Tests/MockFileSystemTests.cs
> doc: add examples for working with ACL and SafeFileHandle

- .github/workflows/release.yml
- Docs/AccessControl.md
- Docs/Compression.md
> fix: incorrect link in README.md on nuget.org

- .github/workflows/build.yml
- .github/workflows/ci.yml
- .github/workflows/release.yml
- Feature.Flags.props
- Tests/Directory.Build.props
- Tests/Testably.Abstractions.Parity.Tests/Net48ParityTests.cs
- Tests/Testably.Abstractions.Tests/TestHelpers/Polyfills/StringExtensions.cs
- Tests/Testably.Abstractions.Tests/TestHelpers/Usings.cs
Update the used .NET Framework version from `net472` to `net48`.
> refactor: update .NET Framework to 4.8 for testing purposes

- Source/Testably.Abstractions.Interface/Testably.Abstractions.Interface.csproj
Update version of `System.IO.Abstractions` to `v19.1.14`
> chore: update version from System.IO.Abstractions to 19.1.14

- Source/Testably.Abstractions.Testing/FileSystem/DriveInfoMock.cs
- Source/Testably.Abstractions.Testing/FileSystemInitializerExtensions.cs
- Source/Testably.Abstractions.Testing/Helpers/FilePlatformIndependenceExtensions.cs
- Source/Testably.Abstractions.Testing/MockFileSystem.cs
- Source/Testably.Abstractions.Testing/MockFileSystemExtensions.cs
- Tests/Testably.Abstractions.Testing.Tests/FileSystemInitializerExtensionsTests.cs
- Tests/Testably.Abstractions.Testing.Tests/MockFileSystemTests.cs
- Tests/Testably.Abstractions.Tests/FileSystem/Path/Tests.cs
> fix: initialize filesystem in drive of current directory

- Source/Testably.Abstractions.Testing/TimeSystem/ITimerMock.cs
- Source/Testably.Abstractions.Testing/TimeSystem/TimerMock.cs
- Source/Testably.Abstractions.Testing/TimeSystem/TimerStrategy.cs
Improve errors and missing data in the documentations from the timer implementation from
- #270
> doc: improve documentation in Timers

- .github/stryker/Stryker.Config.json
- Source/Testably.Abstractions.Testing/Helpers/ExceptionFactory.cs
- Source/Testably.Abstractions.Testing/TimeSystem/TimerMock.cs
- Tests/Testably.Abstractions.Testing.Tests/FileSystem/FileSystemExtensibilityTests.cs
- Tests/Testably.Abstractions.Testing.Tests/RandomSystem/RandomSystemExtensibilityTests.cs
- Tests/Testably.Abstractions.Testing.Tests/TimeSystem/TimeSystemExtensibilityTests.cs
- Tests/Testably.Abstractions.Testing.Tests/TimeSystem/TimerFactoryMockTests.cs
- Tests/Testably.Abstractions.Testing.Tests/TimeSystem/TimerMockTests.cs
- Tests/Testably.Abstractions.Tests/FileSystem/FileSystemWatcher/Tests.cs
- Tests/Testably.Abstractions.Tests/TimeSystem/TimerFactoryTests.cs
Enhance mutation testing coverage by adding tests for missing edge cases.
> coverage: improve stryker coverage for Timer functions 

- README.md
- Tests/Testably.Abstractions.Tests/FileSystem/File/ResolveLinkTargetTests.cs
Mention the new Timer interface and improve the example initialization.
> docs: improve README.md

- .github/workflows/stryker.yml
Fix stryker version to 3.7.1 due to https://github.com/stryker-mutator/stryker-net/issues/2499.
> fix: change stryker.net version to 3.7.1

- Directory.Packages.props
Update the following dependencies:
- xunit.skippablefact to v1.4.13
- testably.abstractions to v2.3.1
- testably.abstractions.testing to v2.3.1
- xunit to v2.5.0
- xunit.runner.visualstudio to v2.5.0
> chore(deps): update dependencies

- Directory.Packages.props
- Tests/Testably.Abstractions.Testing.Tests/FileSystemInitializer/DirectoryCleanerTests.cs
- Tests/Testably.Abstractions.Testing.Tests/FileSystemInitializer/DirectoryDescriptionTests.cs
- Tests/Testably.Abstractions.Testing.Tests/FileSystemInitializer/FileSystemInitializerTests.cs
- Tests/Testably.Abstractions.Tests/FileSystem/File/CopyTests.cs
- Tests/Testably.Abstractions.Tests/FileSystem/File/EncryptDecryptTests.cs
- Tests/Testably.Abstractions.Tests/FileSystem/File/MoveTests.cs
- Tests/Testably.Abstractions.Tests/FileSystem/File/ReplaceTests.cs
- Tests/Testably.Abstractions.Tests/FileSystem/FileInfo/CopyToTests.cs
- Tests/Testably.Abstractions.Tests/FileSystem/FileInfo/MoveToTests.cs
- Tests/Testably.Abstractions.Tests/FileSystem/FileInfo/ReplaceTests.cs
- Tests/Testably.Abstractions.Tests/FileSystem/FileStream/OptionsTests.cs
Use `HasAttribute` assertion extension
> refactor: update FluentAssertions extensions

- .github/mergify.yml
Add a [mergify.yml](https://github.com/TestableIO/System.IO.Abstractions/blob/main/.github/mergify.yml) file.
> feat: add mergify configuration file

- Source/Testably.Abstractions.Testing/Helpers/EncryptionHelper.cs
- Tests/Testably.Abstractions.AccessControl.Tests/DirectoryAclExtensionsTests.cs
- Tests/Testably.Abstractions.AccessControl.Tests/DirectoryInfoAclExtensionsTests.cs
- Tests/Testably.Abstractions.AccessControl.Tests/FileAclExtensionsTests.cs
- Tests/Testably.Abstractions.AccessControl.Tests/FileInfoAclExtensionsTests.cs
- Tests/Testably.Abstractions.AccessControl.Tests/FileStreamAclExtensionsTests.cs
- Tests/Testably.Abstractions.AccessControl.Tests/TestHelpers/FileSystemSecurityExtensions.cs
- Tests/Testably.Abstractions.Testing.Tests/FileSystemInitializer/DirectoryDescriptionTests.cs
- Tests/Testably.Abstractions.Testing.Tests/FileSystemInitializer/FileDescriptionTests.cs
- Tests/Testably.Abstractions.Testing.Tests/FileSystemInitializer/FileSystemInitializerTests.cs
- Tests/Testably.Abstractions.Testing.Tests/Helpers/PathHelperTests.cs
Improve tests for
- AccessControl project
- FileSystemInitializer
- EncryptionHelper
- PathHelper
> refactor: improve test coverage

- .github/workflows/release.yml
> fix: error in release pipeline

- Feature.Flags.props
- Tests/Testably.Abstractions.Tests/FileSystem/DirectoryInfoFactory/Tests.cs
- #381 
Initial preparations for supporting .NET8.0:
- Refactor `Feature.Flags.props`
- Fix expected message for "NullCharacter" exception
> refactor: prepare support for .NET 8.0

- Source/Testably.Abstractions.Testing/FileSystem/DriveInfoMock.cs
- Source/Testably.Abstractions.Testing/FileSystem/FileSystemWatcherMock.cs
- Source/Testably.Abstractions.Testing/FileSystem/PathMock.cs
- Source/Testably.Abstractions.Testing/Helpers/Execute.cs
- Source/Testably.Abstractions.Testing/Helpers/FilePlatformIndependenceExtensions.cs
- Source/Testably.Abstractions.Testing/Helpers/PathHelper.cs
- Source/Testably.Abstractions.Testing/Storage/InMemoryLocation.cs
- Source/Testably.Abstractions.Testing/Storage/InMemoryStorage.cs
Fix `System.IO.Path` usage and sonar issues
> refactor: fix sonar issues

- .github/workflows/build.yml
- .github/workflows/ci.yml
Create and upload coverage information for the .NET Framework tests.
> feat: collect coverage information for .NET Framework

- .github/workflows/build.yml
- .github/workflows/ci.yml
https://github.com/stryker-mutator/stryker-net/issues/3103
> fix: use explicit `Stryker` version 4.3.0

- renovate.json
Add a "dependencies" label to automatically created PRs from [dependabot](https://github.com/dependabot)
> refactor: add "dependencies" label for dependabot PRs

- .github/workflows/build.yml
Add the option to [manually trigger a workflow](https://docs.github.com/en/actions/managing-workflow-runs-and-deployments/managing-workflow-runs/manually-running-a-workflow).
> refactor: allow workflow dispatch for `build.yml`

- .github/workflows/build.yml
Remove incorrect `needs` in build.yml
> fix: build pipeline

- .github/workflows/ci.yml
- Remove disabled mutation tests
- Run static code analysis only for @vbreuss
> refactor: cleanup ci pipeline
