Testably/Testably.Abstractions

README.md

The images in the `README.md` have to come from trusted sources to be displayed correctly on nuget.org.
According to [this linked resource](https://learn.microsoft.com/en-us/nuget/nuget-org/package-readme-on-nuget-org#allowed-domains-for-images-and-badges), one of the sources is `raw.githubusercontent.com`, so changing the image url in the README.md should display without warning on the packages on nuget.org, e.g. [Testably.Abstractions](https://www.nuget.org/packages/Testably.Abstractions/).

doc: update image source in README.md for nuget.org

---

Source/Directory.Build.props

Automatically create [`snupkg` symbol packages](https://github.com/NuGet/docs.microsoft.com-nuget/blob/main/docs/create-packages/Symbol-Packages-snupkg.md) to be pushed alongside the normal nuget packages.

feat: Add symbols snupgk packages

---

Source/Testably.Abstractions.Testing/FileSystemMock.DirectoryMock.cs
Source/Testably.Abstractions.Testing/FileSystemMock.FileInfoMock.cs
Tests/Testably.Abstractions.Tests/FileSystemDirectoryTests.cs
Tests/Testably.Abstractions.Tests/FileSystemDriveInfoFactoryTests.cs

Implement the following methods in the DirectoryMock:
- `GetLogicalDrives()`
- `GetParent()`

feat: implement missing methods on `DirectoryMock`

---

Source/Testably.Abstractions.Testing/FileSystemMock.FileInfoMock.cs
Source/Testably.Abstractions.Testing/FileSystemMock.FileMock.cs
Source/Testably.Abstractions.Testing/FileSystemMock.FileStreamMock.cs
Source/Testably.Abstractions.Testing/FileSystemMock.FileSystemInfoMock.cs
Source/Testably.Abstractions.Testing/Internal/ExceptionFactory.cs
Source/Testably.Abstractions/FileSystem.FileSystemInfoWrapper.cs
Tests/Testably.Abstractions.Tests/FileSystemDriveInfoFactoryTests.cs
Tests/Testably.Abstractions.Tests/FileSystemFileInfoTests.cs
Tests/Testably.Abstractions.Tests/FileSystemFileStreamTests.FileAccess.cs
Tests/Testably.Abstractions.Tests/FileSystemFileStreamTests.cs
Tests/Testably.Abstractions.Tests/FileSystemFileSystemInfoTests.cs
Tests/Testably.Abstractions.Tests/FileSystemTests.cs
Tests/Testably.Abstractions.Tests/Testing/FileSystemInitializerTests.cs

Implement the logic with getting/setting attributes that differ on different operating systems.
Additionally improve unit test coverage and fix some minor bugs:
- `IFileInfo.DirectoryName`
returned only the name and not the full path in FileInfoMock
- `IFileInfo.IsReadOnly`
was not yet implemented in FileInfoMock
- `FileSystemStream.SetLength`
should throw an exception when the stream has no write access
- `FileInfoWrapper`
didn't use Attributes from wrapped instance

feat: implement Get/Set Attributes on `FileSystemInfo`

---

Source/Testably.Abstractions.Testing/FileSystemMock.DirectoryInfoFactoryMock.cs
Source/Testably.Abstractions.Testing/FileSystemMock.DriveInfoFactoryMock.cs
Source/Testably.Abstractions.Testing/FileSystemMock.DriveInfoMock.cs
Source/Testably.Abstractions.Testing/FileSystemMock.FileInfoFactoryMock.cs
Source/Testably.Abstractions.Testing/Storage/InMemoryLocation.cs
Source/Testably.Abstractions.Testing/Storage/InMemoryStorage.cs
Source/Testably.Abstractions/FileSystem.DirectoryInfoFactory.cs
Source/Testably.Abstractions/FileSystem.DriveInfoFactory.cs
Source/Testably.Abstractions/FileSystem.DriveInfoWrapper.cs
Source/Testably.Abstractions/FileSystem.FileInfoFactory.cs
Source/Testably.Abstractions/IFileSystem.IDirectoryInfoFactory.cs
Source/Testably.Abstractions/IFileSystem.IDriveInfoFactory.cs
Source/Testably.Abstractions/IFileSystem.IFileInfoFactory.cs
Tests/Testably.Abstractions.Tests/FileSystemDirectoryInfoFactoryTests.cs
Tests/Testably.Abstractions.Tests/FileSystemDirectoryTests.Exists.cs
Tests/Testably.Abstractions.Tests/FileSystemFileInfoFactoryTests.cs
Tests/Testably.Abstractions.Tests/FileSystemFileInfoTests.Replace.cs
Tests/Testably.Abstractions.Tests/FileSystemFileStreamTests.cs
Tests/Testably.Abstractions.Tests/FileSystemFileTests.Exists.cs
Tests/Testably.Abstractions.Tests/FileSystemFileTests.Replace.cs

Allow FileInfoFactory.Wrap, DirectoryInfoFactory.Wrap and DriveInfoFactory.Wrap to receive `null`.

refactor: improve test coverage & allow null for Wrap factory methods

---

Source/Testably.Abstractions.Testing/Internal/PathHelper.cs
Source/Testably.Abstractions.Testing/Storage/InMemoryStorage.cs
Source/Testably.Abstractions.Testing/Testably.Abstractions.Testing.csproj
Testably.Abstractions.sln
Tests/Testably.Abstractions.Testing.Tests/FilePlatformIndependenceExtensionsTests.cs
Tests/Testably.Abstractions.Testing.Tests/FileSystemInitializerTests.cs
Tests/Testably.Abstractions.Testing.Tests/FileSystemMockTests.cs
Tests/Testably.Abstractions.Testing.Tests/Internal/EncryptionHelperTests.cs
Tests/Testably.Abstractions.Testing.Tests/Internal/FileSystemExtensionsTests.cs
Tests/Testably.Abstractions.Testing.Tests/Internal/PathHelperTests.cs
Tests/Testably.Abstractions.Testing.Tests/NotificationTests.cs
Tests/Testably.Abstractions.Testing.Tests/RandomProviderGeneratorTests.cs
Tests/Testably.Abstractions.Testing.Tests/RandomProviderTests.cs
Tests/Testably.Abstractions.Testing.Tests/RandomSystemExtensionsTests.cs
Tests/Testably.Abstractions.Testing.Tests/TestHelpers/Test.cs
Tests/Testably.Abstractions.Testing.Tests/TestHelpers/TimeTestHelper.cs
Tests/Testably.Abstractions.Testing.Tests/TestHelpers/Usings.cs
Tests/Testably.Abstractions.Testing.Tests/Testably.Abstractions.Testing.Tests.csproj
Tests/Testably.Abstractions.Testing.Tests/TimeProviderTests.cs
Tests/Testably.Abstractions.Testing.Tests/TimeSystemMockCallbackHandlerTests.cs
Tests/Testably.Abstractions.Testing.Tests/TimeSystemMockTests.cs
Tests/Testably.Abstractions.Tests/DependencyInjectionTests.cs
Tests/Testably.Abstractions.Tests/TestHelpers/TimeTestHelper.cs
Tests/stryker-config-testing.json

Add separate test project for `Testably.Abstractions.Testing` which gets access to internal methods/classes.

refactor: add separate testing test project

---

Source/Testably.Abstractions.Testing/Notification.cs
Tests/Testably.Abstractions.Testing.Tests/NotificationTests.cs

In #80 the simplification in `Notification` was incorrect.
Add a test to demonstrate the incorrect behaviour and undo the incorrect changes.

fix: incorrect simplification in Notification

---

Source/Testably.Abstractions.Testing/Internal/EncryptionHelper.cs
Source/Testably.Abstractions.Testing/Storage/InMemoryLocation.cs
Tests/Testably.Abstractions.Testing.Tests/Storage/InMemoryContainerTests.cs
Tests/Testably.Abstractions.Testing.Tests/Storage/InMemoryLocationTests.cs
Tests/Testably.Abstractions.Testing.Tests/Storage/NullContainerTests.cs
Tests/Testably.Abstractions.Tests/FileSystemDirectoryTests.Times.cs
Tests/stryker-config-testing.json

Add tests or simplify implementation due to Stryker analysis:
- Exclude dummy encryption and ExceptionFactory manipulation from stryker
- Add tests for `NullContainer`, `InMemoryLocation` and `InMemoryContainer`

refactor: improve Stryker coverage

---

Source/Testably.Abstractions.Testing/Storage/InMemoryContainer.cs
Tests/Testably.Abstractions.Testing.Tests/Storage/InMemoryStorageTests.cs
Tests/Testably.Abstractions.Testing.Tests/TestHelpers/LockableContainer.cs

Add a test case for the rollback functionality on directory move in the `InMemoryStorage` when a file is locked.

refactor: add test case for rollback on directory move

---

Tests/Testably.Abstractions.Tests/FileSystemFileInfoFactoryTests.cs

test: add test for `PathTooLongException` on .NET Framework

---

Source/Testably.Abstractions.Testing/FileSystemMock.FileMock.cs
Source/Testably.Abstractions.Testing/FileSystemMock.FileSystemInfoMock.cs
Source/Testably.Abstractions.Testing/Storage/InMemoryStorage.cs
Tests/Testably.Abstractions.Tests/FileSystem/Directory/FileSystemDirectoryTests.EnumerateFiles.cs
Tests/Testably.Abstractions.Tests/FileSystem/Directory/FileSystemDirectoryTests.GetDirectories.cs
Tests/Testably.Abstractions.Tests/FileSystem/DirectoryInfo/FileSystemDirectoryInfoTests.MoveTo.cs
Tests/Testably.Abstractions.Tests/FileSystem/File/FileSystemFileTests.Create.cs
Tests/Testably.Abstractions.Tests/FileSystem/File/FileSystemFileTests.Exists.cs
Tests/Testably.Abstractions.Tests/FileSystem/File/FileSystemFileTests.Move.cs
Tests/Testably.Abstractions.Tests/FileSystem/File/FileSystemFileTests.OpenRead.cs
Tests/Testably.Abstractions.Tests/FileSystem/File/FileSystemFileTests.OpenWrite.cs
Tests/Testably.Abstractions.Tests/FileSystem/File/FileSystemFileTests.ReadAllBytes.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileInfoFactory/FileSystemFileInfoFactoryTests.cs

- Fix a bug in `File.Exists` when providing an empty string as `path` parameter
- Make path case insensitive when enumerating on directories also in .NET Framework
- GetBytes don't return the array instance so that the file content is read-only
*Also add some tests that cover certain other edge cases, that were already implemented correctly.*

fix: various edge case inconsistencies

---

Source/Testably.Abstractions.Testing/Notification.cs
Tests/Testably.Abstractions.Testing.Tests/FileSystemMock/FileSystemMockExtensionsTests.cs
Tests/Testably.Abstractions.Testing.Tests/FileSystemMock/InterceptionHandlerExtensionsTests.cs
Tests/Testably.Abstractions.Testing.Tests/FileSystemMock/InterceptionHandlerTests.cs
Tests/Testably.Abstractions.Testing.Tests/FileSystemMock/NotificationHandlerTests.cs
Tests/Testably.Abstractions.Testing.Tests/Notification/NotificationTests.cs

Clarify functionality of the extension methods `Execute` in the `Notification` class by renaming it to `ExecuteWhileWaiting`

refactor: rename `Execute` to `ExecuteWhileWaiting` for notifications

---

Source/Testably.Abstractions.Testing/TimeSystemMock.ITimeProvider.cs
Source/Testably.Abstractions.Testing/TimeSystemMock.TimeProviderMock.cs
Tests/Testably.Abstractions.Testing.Tests/TimeSystemMock/TimeSystemMockTests.cs

This allows different tasks or threads to have distinct times.

feat: change current time in `TimeSystemMock` to be "AsyncLocal"

---

Tests/Testably.Abstractions.Tests/FileSystem/FileSystemWatcher/FileSystemFileSystemWatcherTests.IncludeSubdirectories.cs

The test `FileSystemFileSystemWatcherTests.IncludeSubdirectories_SetToTrue_ShouldTriggerNotificationOnSubdirectories` is brittle on Linux and Mac and should be skipped.

fix: skip brittle test

---

.github/workflows/pr.yml

Remove `test` and replace it with `coverage` as valid type for [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/)

refactor: Add "coverage" type for conventional commits

---

Source/Testably.Abstractions.Testing/FileSystemMock.DirectoryMock.cs
Source/Testably.Abstractions.Testing/FileSystemMock.FileSystemInfoMock.cs
Source/Testably.Abstractions.Testing/Internal/FileSystemExtensions.cs
Source/Testably.Abstractions.Testing/Storage/InMemoryStorage.cs
Tests/Testably.Abstractions.Tests/FileSystem/Directory/FileSystemDirectoryTests.EnumerateDirectories.cs
Tests/Testably.Abstractions.Tests/FileSystem/Directory/FileSystemDirectoryTests.EnumerateFiles.cs
Tests/Testably.Abstractions.Tests/FileSystem/DirectoryInfo/FileSystemDirectoryInfoTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/File/FileSystemFileTests.Copy.cs
Tests/Testably.Abstractions.Tests/FileSystem/File/FileSystemFileTests.Exists.cs
Tests/Testably.Abstractions.Tests/FileSystem/File/MockFileSystemTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileInfo/FileSystemFileInfoTests.CopyTo.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileInfo/FileSystemFileInfoTests.MoveTo.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileInfo/FileSystemFileInfoTests.Replace.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileStream/FileSystemFileStreamTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileSystemTests.ExtensionPoints.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileSystemTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileSystemWatcher/FileSystemFileSystemWatcherTests.Filter.cs
Tests/Testably.Abstractions.Tests/FileSystem/MockFileSystemTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/Path/FileSystemPathTests.GetFullPath.cs
Tests/Testably.Abstractions.Tests/FileSystem/RealFileSystemTests.cs
Tests/Testably.Abstractions.Tests/TestHelpers/Test.cs
Tests/Testably.Abstractions.Tests/TimeSystem/DateTime/RealTimeSystemTests.cs
Tests/Testably.Abstractions.Tests/TimeSystem/Task/RealTimeSystemTests.cs

Test or fix the following issues from [System.IO.Abstractions](https://github.com/TestableIO/System.IO.Abstractions/issues):
- [\#353: TestingHelper.File.Copy initialises contents via object reference](https://github.com/TestableIO/System.IO.Abstractions/issues/353)
- [\#397: Casting MockFileStream to Stream and then disposing it does not cause subsequent calls to throw ObjectDisposedException](https://github.com/TestableIO/System.IO.Abstractions/issues/397)
- [\#402: EnumerateDirectories returns directories with trailing \ slash](https://github.com/TestableIO/System.IO.Abstractions/issues/402)
- [\#405: MockFileSystem consistency issue with slash/backslash paths on Windows](https://github.com/TestableIO/System.IO.Abstractions/issues/405)
- [\#425: Path normalization doesn't match …

fix: test and fix issues from `System.IO.Abstractions`

---

Source/Testably.Abstractions.Testing/FileSystemInitializer.DirectoryCleaner.cs
Source/Testably.Abstractions.Testing/Internal/ExceptionFactory.cs
Source/Testably.Abstractions.Testing/Storage/InMemoryStorage.cs
Tests/Testably.Abstractions.Tests/FileSystem/Directory/FileSystemDirectoryTests.Move.cs
Tests/Testably.Abstractions.Tests/FileSystem/File/FileSystemFileTests.Copy.cs
Tests/Testably.Abstractions.Tests/FileSystem/File/FileSystemFileTests.Move.cs
Tests/Testably.Abstractions.Tests/FileSystem/File/FileSystemFileTests.Replace.cs

This applies to `File.Move`, `File.Copy`, `File.Replace` and `Directory.Replace`:
In all instances, when the destination directory does not exist, the file system should throw a `DirectoryNotFoundException`.
*See also [\#551 MockDirectory.Move does not throw exception if (part of the) target's parent folder does not exist](https://github.com/TestableIO/System.IO.Abstractions/issues/551).*

fix: throw `DirectoryNotFoundException` when the destination directory does not exist

---

README.md

Use an absolute path to the examples section in the readme, so that it is also rendered correctly on [Nuget.org](https://www.nuget.org/packages/Testably.Abstractions)

doc: use absolute link path in README.md

---

Source/Testably.Abstractions.Testing/FileSystemInitializer.cs
Source/Testably.Abstractions.Testing/FileSystemMock.DirectoryMock.cs
Source/Testably.Abstractions.Testing/Internal/FileSystemExtensions.cs
Source/Testably.Abstractions.Testing/Internal/PathHelper.cs
Source/Testably.Abstractions.Testing/Storage/InMemoryLocation.cs
Tests/Testably.Abstractions.Testing.Tests/FileSystemInitializer/FileSystemInitializerTests.cs
Tests/Testably.Abstractions.Testing.Tests/Internal/PathHelperTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/Directory/FileSystemDirectoryTests.EnumerateFileSystemInfos.cs
Tests/Testably.Abstractions.Tests/FileSystem/Directory/FileSystemDirectoryTests.EnumerateFiles.cs
Tests/Testably.Abstractions.Tests/FileSystem/Directory/FileSystemDirectoryTests.GetFileSystemInfos.cs
Tests/Testably.Abstractions.Tests/FileSystem/Directory/FileSystemDirectoryTests.GetFiles.cs
Tests/Testably.Abstractions.Tests/FileSystem/Directory/FileSystemDirectoryTests.Move.cs
Tests/Testably.Abstractions.Tests/FileSystem/Directory/FileSystemDirectoryTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/DirectoryInfo/FileSystemDirectoryInfoTests.MoveTo.cs

Correctly set the current directory to a fully qualified path.
When initializing the file system via the `InitializeIn` method, set the current directory (see `Directory.GetCurrentDirectory()`) to the used base path.

fix: set current directory correctly

---

README.md

Change the order of the badges, so that the current version on [Nuget.org](https://www.nuget.org/packages/Testably.Abstractions) is the first badge.

doc: change order of badges

---

Source/Testably.Abstractions.Testing/Notification.cs
Tests/Testably.Abstractions.Testing.Tests/FileSystemMock/InterceptionHandlerExtensionsTests.cs
Tests/Testably.Abstractions.Testing.Tests/FileSystemMock/InterceptionHandlerTests.cs
Tests/Testably.Abstractions.Testing.Tests/FileSystemMock/NotificationHandlerExtensionsTests.cs
Tests/Testably.Abstractions.Testing.Tests/FileSystemMock/NotificationHandlerTests.cs

Execute the `executeWhanWaiting` callback in a separate thread, so that the timeout setting is respected when the execute while waiting callback is blocked.
The following code should throw a `TimeoutException` after 1s:
```csharp
FileSystemMock fileSystem = new();
fileSystem.Notify
.OnCreated(FileSystemTypes.File, _ => { })
.ExecuteWhileWaiting(() =>
{
Thread.Sleep(3000);
fileSystem.File.Create("foo.txt");
})
// If a timeout is provided, this will throw a TimeoutException if no event was triggered within 1000ms
.Wait(timeout: 1000);
```

fix: notification execute while waiting callback blocks the timeout

---

Source/Testably.Abstractions.Testing/Internal/EncryptionHelper.cs
Source/Testably.Abstractions.Testing/Internal/EnumerationOptionsHelper.cs
Source/Testably.Abstractions.Testing/Internal/ExceptionFactory.cs
Source/Testably.Abstractions.Testing/Internal/Execute.cs
Source/Testably.Abstractions.Testing/Internal/FilePlatformIndependenceExtensions.cs
Source/Testably.Abstractions.Testing/Internal/PathHelper.cs
Source/Testably.Abstractions.Testing/Storage/InMemoryContainer.cs
Source/Testably.Abstractions.Testing/Storage/InMemoryLocation.cs
Source/Testably.Abstractions.Testing/Storage/NullContainer.cs
Source/Testably.Abstractions/FileSystem.DriveInfoWrapper.cs

Remove the `ExcludeFromCodeCoverage` attribute everywhere except for the "Polyfill" classes.

refactor: remove `ExcludeFromCodeCoverage` attribute

---

Tests/Testably.Abstractions.Testing.Tests/FileSystemMock/InterceptionHandlerExtensionsTests.cs
Tests/Testably.Abstractions.Tests/TimeSystem/Task/RealTimeSystemTests.cs

The [release build for v0.7.0](https://github.com/Testably/Testably.Abstractions/actions/runs/3284226067/attempts/2) failed sometimes due to `Testably.Abstractions.Tests.TimeSystem.Task.RealTimeSystemTests+TaskTests.Delay_Milliseconds_Canceled_ShouldDelayForSpecifiedMilliseconds`.
The reason was a too tight timeout sometimes not reached on the build system.

fix: harden sometimes failing test

---

Source/Testably.Abstractions.Testing/FileSystemMock.DriveInfoMock.cs
Source/Testably.Abstractions.Testing/Internal/ExceptionFactory.cs
Source/Testably.Abstractions.Testing/Storage/NullContainer.cs
Source/Testably.Abstractions/FileSystem.DriveInfoWrapper.cs
Tests/Testably.Abstractions.Testing.Tests/Storage/NullContainerTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/DriveInfo/FileSystemDriveInfoTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/DriveInfo/MockFileSystemTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/DriveInfo/RealFileSystemTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/DriveInfoFactory/FileSystemDriveInfoFactoryTests.cs
Tests/stryker-config-testing.json

- Add tests for `NullContainer`
- Add tests for `VolumeLabel` on `DriveInfo`
- Exclude OS-Specific tests from Stryker

refactor: improve test coverage

---

.github/workflows/release.yml
.github/workflows/stryker.yml
README.md
Tests/Testably.Abstractions.AccessControl.Tests/DirectoryAclExtensionsTests.cs
Tests/Testably.Abstractions.AccessControl.Tests/DirectoryInfoAclExtensionsTests.cs
Tests/Testably.Abstractions.AccessControl.Tests/FileAclExtensionsTests.cs
Tests/Testably.Abstractions.AccessControl.Tests/FileInfoAclExtensionsTests.cs
Tests/Testably.Abstractions.AccessControl.Tests/FileStreamAclExtensionsTests.cs
Tests/Testably.Abstractions.AccessControl.Tests/TestHelpers/FileSystemSecurityExtensions.cs
Tests/Testably.Abstractions.AccessControl.Tests/Testably.Abstractions.AccessControl.Tests.csproj
Tests/Testably.Abstractions.Tests/FileSystem/FileStream/FileSystemFileStreamTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileSystemInfo/FileSystemFileSystemInfoTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileSystemTests.ExtensionContainer.cs
Tests/stryker-config-testing.json

As "AccessControl" is only supported, Stryker should run on Windows for this project.
- Improve tests to also run on the real file system
- Add tests for `ExtensionContainer`

refactor: run Stryker on windows for AccessControl project

---

Source/Testably.Abstractions.Testing/Storage/IStorageLocation.cs
Source/Testably.Abstractions.Testing/Storage/InMemoryLocation.cs
Source/Testably.Abstractions.Testing/Storage/InMemoryStorage.cs
Tests/Testably.Abstractions.Testing.Tests/Storage/InMemoryLocationTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/File/FileSystemFileTests.WriteAllText.cs

When writing a file to a directory that doesn't exist, the file system should throw a `DirectoryNotFoundException`.

fix: throw exception when a file is written to a missing directory

---

Source/Testably.Abstractions.AccessControl/DirectoryAclExtensions.cs
Source/Testably.Abstractions.AccessControl/DirectoryInfoAclExtensions.cs
Source/Testably.Abstractions.AccessControl/FileAclExtensions.cs
Source/Testably.Abstractions.AccessControl/FileInfoAclExtensions.cs
Source/Testably.Abstractions.AccessControl/FileStreamAclExtensions.cs
Tests/Testably.Abstractions.AccessControl.Tests/DirectoryAclExtensionsTests.cs
Tests/Testably.Abstractions.AccessControl.Tests/DirectoryInfoAclExtensionsTests.cs

The tests for AccessControl are missing some checks.
Also simplify the implementation when returning values.

fix: missing tests for AccessControl

---

Source/Directory.Build.props
Tests/Directory.Build.props

Some tools (Stryker) don't support using the `$(SolutionDir)` variable in the output path. Use a relative path instead...

refactor: use relative base for output path

---

Source/Testably.Abstractions.Compression/Internal/Execute.cs
Source/Testably.Abstractions.Compression/Testably.Abstractions.Compression.csproj

`Testably.Abstractions.Compression` should only reference `Testably.Abstractions.Interface`.

refactor: remove the dependency on "Testably.Abstractions"

---

Source/Testably.Abstractions.AccessControl/DirectoryAclExtensions.cs
Source/Testably.Abstractions.AccessControl/DirectoryInfoAclExtensions.cs
Source/Testably.Abstractions.AccessControl/FileAclExtensions.cs
Source/Testably.Abstractions.AccessControl/FileInfoAclExtensions.cs
Source/Testably.Abstractions.AccessControl/FileStreamAclExtensions.cs
Source/Testably.Abstractions.AccessControl/Usings.cs
Source/Testably.Abstractions.Interface/FileSystem/IDriveInfo.cs
Source/Testably.Abstractions.Interface/FileSystem/IFile.cs
Source/Testably.Abstractions.Interface/FileSystem/IFileInfo.cs
Source/Testably.Abstractions.Interface/Polyfills/SupportedOsPlatformAttribute.cs
Source/Testably.Abstractions.Interface/Usings.cs
Source/Testably.Abstractions.Testing/FileSystem/DriveInfoMock.cs
Source/Testably.Abstractions.Testing/FileSystem/FileInfoMock.cs
Source/Testably.Abstractions.Testing/FileSystem/FileMock.cs
Source/Testably.Abstractions.Testing/Storage/InMemoryStorage.cs
Source/Testably.Abstractions.Testing/Usings.cs
Source/Testably.Abstractions/FileSystem/DriveInfoWrapper.cs
Source/Testably.Abstractions/FileSystem/FileInfoWrapper.cs
Source/Testably.Abstractions/Usings.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileInfo/FileSystemFileInfoTests.EncryptDecrypt.cs
Tests/Testably.Abstractions.Tests/TestHelpers/Usings.cs

Otherwise this attribute could clash with the real attribute e.g. on .NET 5 in client projects
- #158

refactor: move the `SupportedOSPlatformAttribute` to a distinct namespace

---

.github/workflows/release.yml
README.md

Add a [Codacy](https://app.codacy.com/gh/Testably/Testably.Abstractions/dashboard?branch=main) badge to the readme.md

doc: add Codacy badge to readme

---

.codacy.yml

Markdown files just clutter the analysis page.

refactor: exclude markdown files from Codacy analysis

---

Source/Testably.Abstractions.Testing/FileSystem/DirectoryMock.cs
Source/Testably.Abstractions.Testing/FileSystem/FileMock.cs
Source/Testably.Abstractions.Testing/FileSystem/FileSystemInfoMock.cs
Source/Testably.Abstractions.Testing/Helpers/ExceptionFactory.cs
Source/Testably.Abstractions.Testing/Helpers/PathHelper.cs
Tests/Testably.Abstractions.Tests/FileSystem/Directory/CreateSymbolicLinkTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/DirectoryInfo/CreateAsSymbolicLinkTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/File/CreateSymbolicLinkTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileInfo/CreateAsSymbolicLinkTests.cs

Ensure that correct exceptions are thrown when calling `CreateSymbolicLink` or `CreateAsSymbolicLink` in the following cases:
- a `null` path or target is provided
- an empty path or target is provided
- an invalid path or target is provided
- a path or target containing invalid characters is provided

fix: throw correct exception on CreateSymbolicLink with invalid parameters

---

Source/Testably.Abstractions.Testing/FileSystem/DirectoryInfoMock.cs
Source/Testably.Abstractions.Testing/FileSystem/DirectoryMock.cs
Source/Testably.Abstractions.Testing/Helpers/ExceptionFactory.cs
Source/Testably.Abstractions.Testing/Helpers/FileSystemExtensions.cs
Source/Testably.Abstractions.Testing/Storage/IStorage.cs
Source/Testably.Abstractions.Testing/Storage/InMemoryLocation.cs
Source/Testably.Abstractions.Testing/Storage/InMemoryStorage.cs
Source/Testably.Abstractions.Testing/Storage/StorageExtensions.cs
Tests/Testably.Abstractions.Tests/FileSystem/Directory/SearchFilterTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileInfo/ExistsTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileInfo/Tests.cs

Handle search patterns which start with "../" correctly:
- Throw an ArgumentException on .NET Framework
- Search a directory further up on .NET Core
Also add more test cases to verify the correct behavior of `searchPattern` usage.

fix: handle search pattern correctly in edge cases

---

Tests/Testably.Abstractions.Tests.SourceGenerator/ClassGenerators/TimeSystemClassGenerator.cs
Tests/Testably.Abstractions.Tests/FileSystem/Directory/ExceptionTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/DirectoryInfo/ExceptionTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/DirectoryInfoFactory/ExceptionTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/DriveInfoFactory/ExceptionTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/File/ExceptionTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileInfo/ExceptionTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileInfoFactory/ExceptionTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileStreamFactory/ExceptionTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileSystemInfo/ExceptionTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileSystemWatcherFactory/ExceptionTests.cs
Tests/Testably.Abstractions.Tests/TimeSystem/DateTimeTests.cs
Tests/Testably.Abstractions.Tests/TimeSystem/TaskTests.cs

Add missing tests for the `TimeSystem`.
Also refactor exception tests to include a "because" information

coverage: add missing tests for TimeSystem

---

Source/Testably.Abstractions.Testing/FileSystem/FileMock.cs
Tests/Testably.Abstractions.Testing.Tests/FileSystem/DriveInfoMockTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/File/AppendAllLinesAsyncTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/File/AppendAllLinesTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/File/AppendAllTextTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/File/WriteAllTextTests.cs

Include the encoding preamble in newly created text files.
Ensure correct exception when providing `null` to AppendLines

fix: include byte order mark when creating text files.

---

Examples/Configuration/FileSystemConfiguration.Tests/InitializationTests.cs
Examples/Directory.Build.props
Source/Directory.Build.props
Source/Testably.Abstractions.Testing/FileSystem/DriveInfoFactoryMock.cs
Source/Testably.Abstractions.Testing/FileSystem/DriveInfoMock.cs
Source/Testably.Abstractions.Testing/Storage/IStorageDrive.cs
Source/Testably.Abstractions/FileSystem/DriveInfoWrapper.cs
Tests/Testably.Abstractions.Testing.Tests/MockFileSystemTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/DriveInfo/Tests.cs

`IDriveInfo.GetDrives()` and `IDirectory.GetLogicalDrives()` should not include UNC servers, but only local drives.

fix: exclude UNC servers from GetDrives()

---

Source/Testably.Abstractions.Testing/FileSystem/FileSystemInfoMock.cs
Source/Testably.Abstractions.Testing/Storage/InMemoryStorage.cs
Tests/Testably.Abstractions.Tests/FileSystem/File/DeleteTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileInfo/DeleteTests.cs

In this case a `DirectoryNotFoundException` should be thrown.

fix: throw exception when trying to delete a file in a missing directory

---

Source/Testably.Abstractions.Testing/FileSystem/FileInfoMock.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileInfo/LengthTests.cs

Throw the correct exception when trying to access the Length property of a `IFileInfo` that points to a directory.

fix: throw exception when trying to read the length of a directory

---

Source/Testably.Abstractions.Testing/FileSystem/FileStreamMock.cs
Source/Testably.Abstractions.Testing/Helpers/PathHelper.cs
Tests/Testably.Abstractions.Tests/FileSystem/File/AppendAllLinesAsyncTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/File/AppendAllLinesTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/File/AppendAllTextAsyncTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/File/AppendAllTextTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/File/CopyTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/File/CreateTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/File/WriteAllTextTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileStream/OptionsTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileStreamFactory/Tests.cs

When trying to open a FileSystemStream on a read-only file with write access, it should throw an `UnauthorizedAccessException`

fix: consider the ReadOnly-Attribute when opening a FileSystemStream

---

Source/Testably.Abstractions.Testing/FileSystem/DirectoryInfoMock.cs
Source/Testably.Abstractions.Testing/FileSystem/FileSystemInfoMock.cs
Tests/Testably.Abstractions.Testing.Tests/MockFileSystemTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/File/CreateTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/File/EncryptDecryptTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileInfo/MoveToTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileInfo/Tests.cs
Tests/Testably.Abstractions.Tests/FileSystem/Path/GetExtensionTests.cs

The `IFileInfo.Extension` should return `"."` when the file name ends with a dot and it is executed on Linux or MacOS.

fix: return correct extension on `IFileInfo`

---

Source/Testably.Abstractions.Testing/Storage/InMemoryLocation.cs
Source/Testably.Abstractions.Testing/Storage/StorageExtensions.cs
Tests/Testably.Abstractions.Tests/FileSystem/Directory/SearchFilterTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/DirectoryInfo/Tests.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileInfo/Tests.cs

The friendly name visible by calling `ToString()` on the `IDirectoryInfo` is incorrect for the Parent on .NET Framework.
It should be
- the absolute path on .NET Core
- the name of the parent directory on .NET Framework
Also throw the correct exception when providing too many instances of "…/" in the search string in e.g. "Directory.GetFileSystemInfos()"

fix: set `ToString()` correctly for IDirectoryInfo.Parent on .NET Framework

---

.github/workflows/build.yml
.github/workflows/release.yml
.github/workflows/stryker.yml

After .NET 7 update the release build is no longer working

fix: release build problems after .NET 7 update

---

Source/Testably.Abstractions.Testing/FileSystem/DefaultSafeFileHandleStrategy.cs
Source/Testably.Abstractions.Testing/FileSystem/FileMock.cs
Source/Testably.Abstractions.Testing/FileSystem/FileStreamFactoryMock.cs
Source/Testably.Abstractions.Testing/FileSystem/ISafeFileHandleStrategy.cs
Source/Testably.Abstractions.Testing/FileSystem/ISafeFileHandlerStrategy.cs
Source/Testably.Abstractions.Testing/FileSystem/NullSafeFileHandleStrategy.cs
Source/Testably.Abstractions.Testing/Helpers/ExceptionFactory.cs
Source/Testably.Abstractions.Testing/MockFileSystem.cs
Tests/Testably.Abstractions.Testing.Tests/FileSystem/DefaultSafeFileHandleStrategyTests.cs
Tests/Testably.Abstractions.Testing.Tests/FileSystem/FileMockTests.cs
Tests/Testably.Abstractions.Testing.Tests/FileSystem/FileStreamFactoryMockTests.cs
Tests/Testably.Abstractions.Testing.Tests/MockFileSystemTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileStreamFactory/SafeFileHandleTests.cs

Replace the simple callback with an interface, so that we can provide multiple implementations for ease of testing:
- `NullSafeFileHandleStrategy` throws an exception
- `DefaultSafeFileHandleStrategy` takes a callback for mapping `SafeFileHandle`s to `SafeFileHandleMock`s.

feat(file): add strategy for dealing with `SafeFileHandle`s

---

.github/stryker/Stryker.Config.Testing.json
Source/Testably.Abstractions.Testing/Helpers/EncryptionHelper.cs
Source/Testably.Abstractions.Testing/Helpers/FilePlatformIndependenceExtensions.cs
Tests/Testably.Abstractions.AccessControl.Tests/TestHelpers/FileSystemSecurityExtensions.cs
Tests/Testably.Abstractions.Testing.Tests/FileSystem/DefaultSafeFileHandleStrategyTests.cs

Fix issues found by SonarCloud after updating to .NET 7 and fix incorrect exclude paths in the Stryker config

refactor: fix sonar issues and stryker config

---

Tests/Testably.Abstractions.AccessControl.Tests/DirectoryAclExtensionsTests.cs
Tests/Testably.Abstractions.AccessControl.Tests/DirectoryInfoAclExtensionsTests.cs
Tests/Testably.Abstractions.AccessControl.Tests/FileAclExtensionsTests.cs
Tests/Testably.Abstractions.AccessControl.Tests/FileInfoAclExtensionsTests.cs

Using "AccessControlSections.All" does violate windows security principles.

fix: use AccessControlSections.None in tests

---

Examples/Directory.Build.props

Currently the example projects use version "0.18.*". This is updated to "1.*", so that it uses the latest release version with `1` as major version.

fix: update version used in Examples to "1.*"

---

.github/workflows/build.yml
.github/workflows/ci.yml
.github/workflows/release.yml
Source/Testably.Abstractions.Testing/FileSystem/DirectoryMock.cs
Source/Testably.Abstractions.Testing/FileSystem/FileMock.cs
Source/Testably.Abstractions.Testing/FileSystem/FileStreamMock.cs
Source/Testably.Abstractions.Testing/Storage/InMemoryContainer.cs
Source/Testably.Abstractions.Testing/Storage/InMemoryStorage.cs
Tests/Testably.Abstractions.Testing.Tests/FileSystem/FileStreamFactoryMockTests.SafeFileHandle.cs
Tests/Testably.Abstractions.Testing.Tests/TestHelpers/Test.cs
Tests/Testably.Abstractions.Tests/FileSystem/Directory/ResolveLinkTargetTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/Directory/Tests.AdjustTimes.cs
Tests/Testably.Abstractions.Tests/FileSystem/File/CopyTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/File/ReadAllBytesTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/File/ReadAllTextTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileInfo/CopyToTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileInfo/ReplaceTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileStream/AdjustTimesTests.cs

Enable tests against real file system to run during CI build.
Fix failing tests, due to time-adjustment not being implemented correctly in all cases.

fix: time-related tests

---

Examples/Directory.Build.props
README.md

In preparation for release 2.0, update the version used in the Examples project to `2.*`
Update README.md to reference System.IO.Abstractions

doc: prepare release 2.0

---

Tests/Testably.Abstractions.Tests/FileSystem/FileInfo/Tests.cs

Based on https://github.com/TestableIO/System.IO.Abstractions/issues/942 add a test for correct behaviour of `FileInfo.IsReadOnly` when the file does not exist.

coverage: add test for IsReadOnly on missing FileInfo

---

.github/workflows/build.yml

Updating the setup-java build to v3 in #249 resulted in build errors due to missing required parameter `distribution`

fix: add distribution to setup-java build task

---

.github/workflows/build.yml

https://community.sonarsource.com/t/build-fail-in-github-set-up-jdk-17-failed/58761/2

fix: update java version for sonarcloud analysis

---

Source/Testably.Abstractions.Testing/TimeSystem/ITimerStrategy.cs
Source/Testably.Abstractions.Testing/TimeSystem/TimerExecution.cs
Source/Testably.Abstractions.Testing/TimeSystem/TimerMock.cs
Source/Testably.Abstractions.Testing/TimeSystem/TimerStrategy.cs
Tests/Testably.Abstractions.Testing.Tests/TimeSystem/TimerMockTests.cs
Tests/Testably.Abstractions.Tests/TimeSystem/TimerTests.cs

Exceptions thrown in the timer callback should be swallowed and thrown on the main thread

fix: Timer should support swallowing exceptions

---

Source/Testably.Abstractions.Testing/TimeSystem/TimerExecution.cs
Source/Testably.Abstractions.Testing/TimeSystem/TimerMock.cs
Tests/Testably.Abstractions.Testing.Tests/FileSystem/FileStreamFactoryMockTests.cs
Tests/Testably.Abstractions.Testing.Tests/FileSystem/FileSystemWatcherFactoryMockTests.cs
Tests/Testably.Abstractions.Testing.Tests/FileSystem/FileSystemWatcherMockTests.cs
Tests/Testably.Abstractions.Testing.Tests/FileSystemInitializer/DirectoryCleanerTests.cs
Tests/Testably.Abstractions.Testing.Tests/NotificationTests.cs
Tests/Testably.Abstractions.Testing.Tests/TimeSystem/TimerMockTests.cs
Tests/Testably.Abstractions.Tests/TimeSystem/TimerTests.cs

Improve test coverage and simplify implementation of `TimerMock`

coverage: improve coverage of TimerMock

---

.github/workflows/test-report.yml

Disable `fail-on-error` in [test-reporter](https://github.com/dorny/test-reporter), as the test tasks themselves fail when an test failed.

fix: disable `fail-on-test` in "Test Report" action

---

Source/Testably.Abstractions/RandomSystem/RandomFactory.cs
Source/Testably.Abstractions/RealFileSystem.cs
Source/Testably.Abstractions/RealRandomSystem.cs
Source/Testably.Abstractions/RealTimeSystem.cs

Avoid redundant object creation in `RealFileSystem`, `RealRandomSystem` and `RealTimeSystem`.

fix: avoid redundant object creation

---

.gitignore
Source/Testably.Abstractions.Testing/MockFileSystem.cs
Source/Testably.Abstractions.Testing/MockFileSystemExtensions.cs
Tests/Testably.Abstractions.Testing.Tests/FileSystem/DriveInfoMockTests.cs
Tests/Testably.Abstractions.Testing.Tests/FileSystemInitializerExtensionsTests.cs
Tests/Testably.Abstractions.Testing.Tests/MockFileSystemTests.cs

Initialize the `MockFileSystem` with the drive from the current directory and support multiple drives in tests.
Add extension method `GetDefaultDrive` on `MockFileSystem` to return the default drive.
*Exclude NCrunch files in `.gitignore`*

feat: initialize `MockFileSystem` with drive from current directory

---

Source/Testably.Abstractions/Testably.Abstractions.csproj
Tests/Helpers/Testably.Abstractions.Tests.SourceGenerator/ClassGenerators/FileSystemClassGenerator.cs
Tests/Testably.Abstractions.Tests/Internal/DirectoryInfoWrapperTests.cs
Tests/Testably.Abstractions.Tests/Internal/DriveInfoWrapperTests.cs
Tests/Testably.Abstractions.Tests/Internal/FileInfoWrapperTests.cs
Tests/Testably.Abstractions.Tests/Internal/FileStreamWrapperTests.cs
Tests/Testably.Abstractions.Tests/Internal/FileSystemExtensibilityTests.cs
Tests/Testably.Abstractions.Tests/Internal/FileSystemInfoWrapperTests.cs
Tests/Testably.Abstractions.Tests/Internal/FileSystemWatcherWrapperTests.cs

Add tests for internal functionality of the `RealFileSystem` to test edge cases.

coverage: add internal tests for `RealFileSystem`

---

Source/Testably.Abstractions.Testing/FileSystemInitializerExtensions.cs

Fix two sonar issues in `FileSystemInitializerExtensions.cs`:
- Use span-based 'string.Concat' and 'AsSpan' instead of 'Substring'
- Use 'string.Contains' instead of 'string.IndexOf' to improve readability
Both issues are deactivated via `#pragma` directives, as the issues don't work under `netstandard2.0`.

fix: sonar issues

---

Source/Testably.Abstractions.Testing/Storage/InMemoryContainer.cs
Tests/Testably.Abstractions.Tests/FileSystem/DirectoryInfo/AttributesTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/File/SetAttributesTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileInfo/AttributesTests.cs

Inspired by https://github.com/TestableIO/System.IO.Abstractions/issues/957:
Correctly set the `Directory` attribute on the mocked file system.

fix: set `Directory` attribute correctly

---

Source/Testably.Abstractions.Testing/RandomSystem/RandomFactoryMock.cs
Source/Testably.Abstractions.Testing/RandomSystem/RandomProviderMock.cs
Tests/Testably.Abstractions.Tests/RandomSystem/RandomFactoryTests.cs

IRandomSystem.Random.Shared should be a thread-static singleton instance (same as on the real [Random](https://learn.microsoft.com/en-us/dotnet/api/system.random.shared#system-random-shared) class).

feat: make Random.Shared thread-static singleton

---

Source/Testably.Abstractions.Testing/Helpers/PathHelper.cs
Source/Testably.Abstractions.Testing/Storage/InMemoryStorage.cs
Tests/Testably.Abstractions.Testing.Tests/Storage/InMemoryStorageTests.cs

Adapt and improve test coverage of `InMemoryStorage`.

coverage: add tests for `InMemoryStorage`

---

Examples/ZipFile/ZipFile/ZipFileHelper.cs
Source/Testably.Abstractions.Testing/FileSystem/DirectoryInfoMock.cs
Source/Testably.Abstractions.Testing/FileSystem/FileMock.cs
Source/Testably.Abstractions.Testing/Helpers/ExceptionFactory.cs
Tests/Testably.Abstractions.Tests/FileSystem/Directory/CreateDirectoryTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/DirectoryInfo/CreateSubdirectoryTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/DirectoryInfo/CreateTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/File/AppendAllLinesAsyncTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/File/AppendAllLinesTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/File/AppendAllTextAsyncTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/File/AppendAllTextTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/File/WriteAllBytesAsyncTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/File/WriteAllBytesTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/File/WriteAllLinesAsyncTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/File/WriteAllLinesTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/File/WriteAllTextAsyncTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/File/WriteAllTextTests.cs

Fix the issue described in https://github.com/TestableIO/System.IO.Abstractions/issues/968.

fix: throw correct exception when creating a file or directory when a conflicting directory or file already exists

---

Source/Testably.Abstractions.Testing/Storage/InMemoryStorage.cs
Tests/Testably.Abstractions.Tests/FileSystem/Path/GetRelativePathTests.cs

Support rooted paths under Windows and ensure that Path.GetRelativePath works on multiple drives.
*This tests and fixes https://github.com/TestableIO/System.IO.Abstractions/issues/728 in Testably.Abstractions...*

fix: support rooted paths under Windows

---

.github/workflows/pr.yml
.github/workflows/release.yml

Add a changelog batch in the Nuget README.md that links to the Github Release for the generated release tag.
**Example-Badge:**
[![Changelog](https://img.shields.io/badge/Changelog-v2.2.0-blue)](https://github.com/Testably/Testably.Abstractions/releases/tag/v2.2.0)

doc: add a changelog batch to the README.md for nuget packages

---

.github/workflows/pr.yml

[Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) suggest `docs` as prefix for documentation changes.

fix: use suggested prefix `docs` for conventional commit pull request titles

---

Source/Testably.Abstractions.Testing/FileSystemInitializerExtensions.cs
Source/Testably.Abstractions.Testing/FileSystemInitializerOptions.cs
Tests/Testably.Abstractions.Testing.Tests/FileSystemInitializerExtensionsTests.cs

Add options to the FileSystemInitializer with the option to automatically create the temporary directory.
If this is not set (or the file system is not initialized) `Path.GetTempPath()` will not exist.
This fixes the issue in System.IO.Abstractions: https://github.com/TestableIO/System.IO.Abstractions/issues/983

feat: add initializer options to create the temporary directory.

---

.github/workflows/release.yml

As the examples now include Drive management examples, they should run on Windows.
The build and ci pipelines were updated with #299, but the release pipeline was overlooked.

fix: run examples on windows

---

Tests/Testably.Abstractions.Tests/FileSystem/DirectoryInfo/CreateTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileInfo/CreateTests.cs

The tests `Create_ShouldRefreshExistsCacheForCurrentItem_ExceptOnNetFramework` introduced in #313 fail on .NET Framework.

fix: failing tests on .NET framework

---

.gitignore
CONTRIBUTING.md

Document the available constants to run tests against the `RealFileSystem` also on the local machine:
- [`ENABLE_REALFILESYSTEMTESTS_IN_DEBUG`](https://github.com/Testably/Testably.Abstractions/blob/main/Tests/Helpers/Testably.Abstractions.Tests.SourceGenerator/ClassGenerators/FileSystemClassGenerator.cs#L59)  
If set, the classes for executing tests against the real file system are created also in DEBUG mode.
- [`INCLUDE_LONGRUNNING_TESTS_ALSO_IN_DEBUG_MODE`](https://github.com/Testably/Testably.Abstractions/blob/main/Tests/Helpers/Testably.Abstractions.TestHelpers/Test.cs#L51)  
In order to increase the test execution speed during development, long running tests are disabled in DEBUG mode.
When this constant is set, the corresponding tests are no longer skipped.
- …

doc: include information for local testing against the `RealFileSystem`

---

CONTRIBUTING.md
Directory.Build.props
Testably.Abstractions.sln

I added a sample Directory.Build.props on the root path and adapted the CONTRIBUTING.md to simplify activating tests for the `RealFileSystem`

feat: Add a sample Directory.Build.props

---

Tests/Testably.Abstractions.Tests/FileSystem/Directory/GetFilesTests.cs

The `GetFiles_MissingDirectory_ShouldThrowDirectoryNotFoundException` test failed because exceptions are thrown in German on my system and with double quotes, therefore I deleted the quotes from the assertion.

fix: Remove single quotes from test

---

Source/Testably.Abstractions.Testing/Helpers/FileSystemExtensions.cs
Tests/Testably.Abstractions.Tests/FileSystem/Directory/GetFilesTests.cs

`FileSystem.Directory.GetFiles(string path)` returns an invalid file path when the argument consists of `..` and two subfolders, when the current directory was located in the first subfolder.
The returned file path contains the second subfolder twice. (e.g. `..\subfolder1\subfolder2\subfolder2\file.txt`)

fix: Support relative paths with multiple subfolders in Directory.GetFiles

---

Source/Testably.Abstractions.Testing/Helpers/FileSystemExtensibility.cs
Source/Testably.Abstractions.Testing/MockFileSystem.cs
Source/Testably.Abstractions.Testing/MockRandomSystem.cs
Source/Testably.Abstractions.Testing/MockTimeSystem.cs
Source/Testably.Abstractions.Testing/Storage/InMemoryContainer.cs
Source/Testably.Abstractions.Testing/Storage/InMemoryStorage.cs

Add `ToString` methods and direct `Container` property to the `MockFileSystem` to simplify debugging.

feat: add `ToString` methods to simplify debugging

---

Source/Testably.Abstractions.Testing/FileSystem/FileSystemInfoMock.cs
Source/Testably.Abstractions.Testing/FileSystem/PathMock.cs
Source/Testably.Abstractions.Testing/Helpers/PathHelper.cs
Source/Testably.Abstractions.Testing/InterceptionHandlerExtensions.cs
Source/Testably.Abstractions.Testing/NotificationHandlerExtensions.cs
Source/Testably.Abstractions.Testing/Storage/InMemoryLocation.cs
Source/Testably.Abstractions.Testing/Storage/InMemoryStorage.cs
Tests/Testably.Abstractions.Tests/FileSystem/Path/ExceptionTests.cs

Throw correct exceptions in `Path.GetFullPath` when the parameter is `null`, empty or invalid.

fix: parameter validation in `Path.GetFullPath`

---

Source/Testably.Abstractions.Interface/Helpers/PathSystemBase.cs
Source/Testably.Abstractions.Testing/FileSystem/PathMock.cs
Tests/Testably.Abstractions.Tests/FileSystem/Path/GetRelativePathTests.cs

Prototype implementation for https://github.com/TestableIO/System.IO.Abstractions/issues/773, similar to [the implementation in .NET Runtime](https://github.com/dotnet/runtime/blob/release/7.0/src/libraries/System.Private.CoreLib/src/System/IO/Path.cs#L886)

fix: implementation of `Path.GetRelativePath`

---

.github/workflows/release.yml

Fix the stryker version to `v3.7.1` on release builds, because the latest version runs in timeouts.

fix: set stryker version to v3.7.1 on release builds

---

Directory.Packages.props
Examples/Directory.Build.props

Remove unnecessary reference to `Testably.Abstractions` as it is indirectly referenced by `Testably.Abstractions.Testing`.

chore: remove unnecessary reference

---

Source/Testably.Abstractions.Testing/MockFileSystem.cs
Source/Testably.Abstractions.Testing/MockTimeSystem.cs
Source/Testably.Abstractions.Testing/Storage/InMemoryStorage.cs
Source/Testably.Abstractions.Testing/TimeProvider.cs
Source/Testably.Abstractions.Testing/TimeSystem/TimeProviderMock.cs
Tests/Testably.Abstractions.Testing.Tests/TimeProviderTests.cs

Add further improvements to the debugging experience after #335.

feat: add `ToString` methods to simplify debugging (2)

---

README.md

The URL for the Codacy Badge changed and needs to be updated.

docs: fix link in Codacy badge

---

Source/Testably.Abstractions.Testing/FileSystemInitializer/DirectoryDescription.cs
Source/Testably.Abstractions.Testing/FileSystemInitializer/FileDescription.cs
Source/Testably.Abstractions.Testing/FileSystemInitializer/FileSystemInfoDescription.cs
Source/Testably.Abstractions.Testing/FileSystemInitializer/FileSystemInitializer.cs
Source/Testably.Abstractions.Testing/FileSystemInitializer/IFileSystemInitializer.cs
Tests/Testably.Abstractions.Testing.Tests/FileSystemInitializer/DirectoryCleanerTests.cs
Tests/Testably.Abstractions.Testing.Tests/FileSystemInitializer/DirectoryDescriptionTests.cs
Tests/Testably.Abstractions.Testing.Tests/FileSystemInitializer/FileDescriptionTests.cs
Tests/Testably.Abstractions.Testing.Tests/FileSystemInitializer/FileSystemInitializerTests.cs

Simplify the initialization of a `IFileSystem` by providing `FileSystemInfoDescription`s to the initializers `With` method, e.g.
```csharp
var fileSystem = new MockFileSystem();
fileSystem.Initialize().With(
new DirectoryDescription("some-empty-directory"),
new FileDescription("filename.txt", "some file content"));
```

feat: simplify initialization of file systems

---

.github/workflows/build.yml
.github/workflows/ci.yml
.github/workflows/release.yml

Use [retry action](https://github.com/marketplace/actions/retry-action) to retry a failed test step once in the build pipeline.

refactor: use retry action for failed tests

---

.github/workflows/build.yml
.github/workflows/release.yml

Rename `sonar.login` in `sonar.token` to get rid of the following warning:
Fixes #354

fix: sonar deprecation warning

---

Directory.Packages.props
Examples/Directory.Build.props
Examples/SafeFileHandle/SafeFileHandle/CustomSafeFileHandleStrategy.cs
Tests/Directory.Build.props
Tests/Helpers/Testably.Abstractions.TestHelpers/Testably.Abstractions.TestHelpers.csproj
Tests/Helpers/Testably.Abstractions.Tests.SourceGenerator/Testably.Abstractions.Tests.SourceGenerator.csproj
Tests/Testably.Abstractions.Testing.Tests/Helpers/PathHelperTests.cs
Tests/Testably.Abstractions.Testing.Tests/RandomProvider.GeneratorTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileSystemWatcher/Tests.cs

Remove dependency on Moq due to its dependency on SponsorLink (see https://github.com/moq/moq/issues/1374)

refactor: remove dependency on Moq

---

renovate.json

See the FAQ entry [`Group all packages starting with abc together in one PR`](https://docs.renovatebot.com/faq/#group-all-packages-starting-with-abc-together-in-one-pr).

feat: add renovate package group for Testably.Abstractions packages

---

.github/workflows/release.yml

Use [softprops/action-gh-release](https://github.com/softprops/action-gh-release) to automatically create Github releases in the release build pipeline.
Also use [apexskier/github-release-commenter](https://github.com/apexskier/github-release-commenter) to add a comment in relevant issues and pull requests.

feat: improve release pipeline to automatically create a Github release

---

Source/Testably.Abstractions.Testing/Helpers/FilePlatformIndependenceExtensions.cs
Tests/Testably.Abstractions.Testing.Tests/NotificationTests.cs
Tests/Testably.Abstractions.Testing.Tests/TimeSystem/TimerMockTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileStream/FileAccessTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileSystemWatcher/Tests.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileSystemWatcher/WaitForChangedTests.cs
Tests/Testably.Abstractions.Tests/TimeSystem/TimerFactoryTests.cs
Tests/Testably.Abstractions.Tests/TimeSystem/TimerTests.cs

Fixes [S2925 Do not use 'Thread.Sleep()' in a test](https://sonarcloud.io/organizations/testably/rules?open=csharpsquid%3AS2925&rule_key=csharpsquid%3AS2925)
*Using `Thread.Sleep` in a test might introduce unpredictable and inconsistent results depending on the environment. Furthermore, it will block the [thread](https://en.wikipedia.org/wiki/Thread_%28computing%29), which means the system resources are not being fully used.*
Fix [S6444 Not specifying a timeout for regular expressions is security-sensitive](https://sonarcloud.io/organizations/testably/rules?open=csharpsquid%3AS6444&rule_key=csharpsquid%3AS6444)
*Not specifying a timeout for regular expressions can lead to a Denial-of-Service attack. Pass a timeout when using `System.Text.RegularExpressions` to process untrusted input …

refactor: avoid `Thread.Sleep` in Tests

---

Source/Testably.Abstractions.Testing/FileSystemInitializer/DirectoryInitializer.cs
Source/Testably.Abstractions.Testing/FileSystemInitializer/FileSystemInitializer.cs
Tests/Testably.Abstractions.Testing.Tests/FileSystemInitializer/FileSystemInitializerTests.cs

Initializing the file system with nested `DirectoryDescriptions` now creates the correct nested path.

fix: `FileSystemInitializer` supports nested directories

---

Source/Testably.Abstractions.Testing/Storage/InMemoryStorage.cs
Tests/Testably.Abstractions.Tests/FileSystem/File/CopyTests.cs

- #381 
`LastAccessTime` is no longer updated for the source file when copying it on OSX.
(see https://github.com/dotnet/runtime/pull/79243 for more details)

feat: support .NET 8.0 | `LastAccessTime` is no longer updated for the source file when copying it on OSX

---

Source/Testably.Abstractions.Testing/FileSystem/FileInfoMock.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileInfo/CreateTextTests.cs

- #381 
`IFileInfo.CreateText` now refreshes the internal cache of the `FileInfo`

feat: support .NET 8.0 | Refresh cache on `IFileInfo.CreateText`

---

Source/Testably.Abstractions.Testing/TimeSystem/TimerFactoryMock.cs
Source/Testably.Abstractions.Testing/TimeSystem/TimerMock.cs
Tests/Helpers/Testably.Abstractions.Tests.SourceGenerator/ClassGenerators/TimeSystemClassGenerator.cs
Tests/Testably.Abstractions.Parity.Tests/ParityTests.cs
Tests/Testably.Abstractions.Testing.Tests/TimeSystem/TimerFactoryMockTests.cs
Tests/Testably.Abstractions.Testing.Tests/TimeSystem/TimerMockTests.cs
Tests/Testably.Abstractions.Tests/TimeSystem/TimerFactoryTests.cs
Tests/Testably.Abstractions.Tests/TimeSystem/TimerTests.cs

- #381 
Change Timer so that it no longer throws `ObjectDisposedException` after being disposed:
(see [this change](https://github.com/dotnet/runtime/commit/5d88ff404de77d78e07ad3de7fa2af270332da22#diff-ca0e15ba4d75ab4c7ce9b34d870658ec3d507a6e88739138e9751b7338b4171d) for more details)

feat: support .NET 8.0 | Timer no longer throws `ObjectDisposedException`

---

Source/Testably.Abstractions.Compression/IZipFile.cs
Source/Testably.Abstractions.Compression/Internal/ZipUtilities.cs
Source/Testably.Abstractions.Compression/ZipFileWrapper.cs
Tests/Testably.Abstractions.Compression.Tests/TestHelpers/MemoryStreamMock.cs
Tests/Testably.Abstractions.Compression.Tests/ZipFile/CreateFromDirectoryTests.cs
Tests/Testably.Abstractions.Compression.Tests/ZipFile/ExtractToDirectoryTests.cs

- #381 
Add new methods for `IZipFile`:
`CreateFromDirectory` and `ExtractToDirectory` now also work with a `Stream`

feat: support .NET 8.0 | Add new methods for `IZipFile`

---

Source/Testably.Abstractions.Interface/Helpers/RandomWrapper.cs
Source/Testably.Abstractions.Interface/RandomSystem/IRandom.cs
Source/Testably.Abstractions.Testing/Helpers/ExceptionFactory.cs
Source/Testably.Abstractions.Testing/RandomSystem/RandomMock.cs
Tests/Testably.Abstractions.Tests/RandomSystem/RandomTests.cs

- #381 
Add new methods for `IRandom`:
- [`GetItems`](https://learn.microsoft.com/en-us/dotnet/api/system.random.getitems?view=net-8.0)
- [`Shuffle`](https://learn.microsoft.com/en-us/dotnet/api/system.random.shuffle?view=net-8.0)

feat: support .NET 8.0 | Add new methods for `IRandom`

---

Directory.Packages.props
Tests/Testably.Abstractions.Testing.Tests/FileSystemInitializerExtensionsTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/Directory/CreateDirectoryTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/Directory/DeleteTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/Directory/ResolveLinkTargetTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/Directory/Tests.cs
Tests/Testably.Abstractions.Tests/FileSystem/DirectoryInfo/CreateSubdirectoryTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/DirectoryInfo/CreateTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/DirectoryInfo/DeleteTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/DirectoryInfo/ExistsTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/DirectoryInfo/Tests.cs
Tests/Testably.Abstractions.Tests/FileSystem/DirectoryInfoFactory/Tests.cs
Tests/Testably.Abstractions.Tests/FileSystem/File/ResolveLinkTargetTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileInfo/CopyToTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileInfo/CreateTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileInfo/CreateTextTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileInfo/DeleteTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileInfo/ExistsTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileInfo/MoveToTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileInfo/OpenTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileInfo/ReplaceTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileInfoFactory/Tests.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileSystemInfo/ResolveLinkTargetTests.cs

Use the `Exist`/`NotExist` fluent assertions for checking if `IFileInfo` or `IDirectoryInfo` exists in the file system.

refactor: use `Exist` and `NotExist` fluent assertions

---

Tests/Testably.Abstractions.Tests/FileSystem/DirectoryInfo/Tests.cs

Fix incorrect nullable warning from SonarCloud:

fix: nullable warning from SonarCloud

---

Tests/Testably.Abstractions.Tests/FileSystem/DirectoryInfo/AttributesTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/File/GetAttributesTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/File/SetAttributesTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileInfo/CopyToTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileInfo/MoveToTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileInfo/ReplaceTests.cs

In .NET 8 a new flag was added to [`FileAttributes`](https://learn.microsoft.com/en-us/dotnet/api/system.io.fileattributes?view=net-8.0): `FileAttributes.None`.
When this attribute is used in the `GetAttributes_ShouldReturnAttributes` test, the test fails.
Now the tested attributes are explicitly specified, so that the tests with FileAttributes as parameter always succeed.
*See [this test run](https://github.com/Testably/Testably.Abstractions/actions/runs/6380040873/job/17313688446?pr=389) in #389.*

fix: explicitly specify `FileAttributes` in tests

---

Source/Testably.Abstractions.Testing/FileSystem/FileInfoMock.cs
Source/Testably.Abstractions.Testing/Storage/InMemoryStorage.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileInfo/ReplaceTests.cs

When replacing a read-only file on Windows, it should throw an UnauthorizedAccessException.

fix: throw UnauthorizedAccessException when replacing a read-only file on Windows

---

Source/Testably.Abstractions.Testing/FileSystem/PathMock.cs
Tests/Testably.Abstractions.Tests/FileSystem/Path/GetFullPathTests.cs

Support relative paths with drive information in `Path.GetFullPath` as described in https://github.com/TestableIO/System.IO.Abstractions/issues/1044.

fix: support relative path with drive information in `Path.GetFullPath`

---

Source/Testably.Abstractions.Testing/Storage/InMemoryStorage.cs
Tests/Testably.Abstractions.Tests/FileSystem/Directory/EnumerateDirectoriesTests.cs

Reproduce the finding from https://github.com/TestableIO/System.IO.Abstractions/pull/1046

fix: `Directory.EnumerateDirectories` with trailing slash in `path`

---

.github/workflows/build.yml
.github/workflows/ci-stryker.yml
.github/workflows/ci.yml
.github/workflows/release.yml
.github/workflows/stryker.yml
Feature.Flags.props
Source/Directory.Build.props
Tests/Directory.Build.props
Tests/Testably.Abstractions.Parity.Tests/Net8ParityTests.cs

Fixes #381 after implementing:
- #388 
- #387
- #386
- #385 
- #384 
- #383
- #382

feat: enable support for .NET 8.0

---

Directory.Packages.props
Examples/Directory.Build.props

Update the used references from Microsoft to `8.0.0` and use .NET 8 in the Examples solution.

feat: update references to net8

---

Source/Testably.Abstractions.Testing/Storage/InMemoryStorage.cs
Tests/Testably.Abstractions.Tests/FileSystem/Directory/DeleteTests.cs

Calling `MockFileSystem.Directory.Delete` with `recursive: true` throws a `DirectoryNotEmptyException` when trying to delete a directory with files in it.
As the documentation of [`Directory.Delete(String, Boolean)`](https://learn.microsoft.com/en-us/dotnet/api/system.io.directory.delete?view=net-8.0#system-io-directory-delete(system-string-system-boolean)) indicates, the method should actually try to delete all files and subfolders instead.

fix: Delete directory recursive should delete files in subfolders

---

Source/Testably.Abstractions.Testing/FileSystem/FileInfoFactoryMock.cs
Source/Testably.Abstractions.Testing/Helpers/PathHelper.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileInfoFactory/Tests.cs

As reported in https://github.com/TestableIO/System.IO.Abstractions/issues/1070, whitespace-only files are treated differently depending on the underlying operating system:
- Windows only supports unicode-whitespace, but throws on filenames with only blanks
- Linux supports both files with only blanks or with unicode-whitespace

fix: handling of whitespace-only filenames

---

Source/Testably.Abstractions.Testing/FileSystem/FileInfoMock.cs
Source/Testably.Abstractions.Testing/FileSystem/FileSystemInfoMock.cs
Source/Testably.Abstractions.Testing/Polyfills/StringExtensionMethods.cs
Tests/Testably.Abstractions.Tests/FileSystem/DirectoryInfoFactory/Tests.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileInfoFactory/Tests.cs

The `FileInfo.Name` property should be empty when created from a path with a trailing `Path.DirectorySeparatorChar`.

fix: use correct empty name for `IFileInfo` with trailing directory separator char

---

.github/workflows/build.yml
.github/workflows/ci-stryker.yml
.github/workflows/ci.yml
.github/workflows/test-report.yml
Testably.Abstractions.sln
renovate.json

Fix the failing build after #444:
- Add the `test-report.yml` pipeline again
- Downgrade the `upload-artifact` and `download-artifact` actions from v4 to v3
- Exclude the two actions from `renovate.json`

fix: failing build

---

Tests/Helpers/Testably.Abstractions.TestHelpers/FileSystemTestBase.cs
Tests/Helpers/Testably.Abstractions.TestHelpers/Test.cs
Tests/Helpers/Testably.Abstractions.Tests.SourceGenerator/ClassGenerators/FileSystemClassGenerator.cs
Tests/Testably.Abstractions.Tests/FileSystem/Directory/CreateDirectoryTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/Directory/ExceptionTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/Directory/GetDirectoryRootTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/Directory/MoveTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/Directory/ResolveLinkTargetTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/Directory/Tests.cs
Tests/Testably.Abstractions.Tests/FileSystem/DirectoryInfo/Tests.cs
Tests/Testably.Abstractions.Tests/FileSystem/DriveInfo/Tests.cs
Tests/Testably.Abstractions.Tests/FileSystem/DriveInfoFactory/Tests.cs
Tests/Testably.Abstractions.Tests/FileSystem/File/CopyTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/File/ExceptionMissingFileTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/File/ExceptionTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/File/MoveTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/File/ReplaceTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/File/ResolveLinkTargetTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileInfoFactory/Tests.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileSystemInfo/ResolveLinkTargetTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/Path/GetFullPathTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/Path/GetRelativePathTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/Path/IsPathFullyQualifiedTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/Path/TrimEndingDirectorySeparatorTests.cs
Tests/Testably.Abstractions.Tests/TestHelpers/FileTestHelper.cs

As a prerequisite to #460 refactor how to handle OS-specific use cases in tests:
- Make the `Test` class non-static and a property of the source-generated test classes
- Replace all calls to the `Test` methods to use the property instead

refactor: use non-static OS selector in tests

---

Source/Testably.Abstractions.Testing/FileSystem/FileMock.cs
Source/Testably.Abstractions.Testing/FileSystem/PathMock.cs
Source/Testably.Abstractions.Testing/Statistics/FileSystemStatistics.cs
Source/Testably.Abstractions.Testing/Statistics/ParameterDescription.cs
Tests/Testably.Abstractions.Testing.Tests/Polyfills/StringExtensionMethods.cs
Tests/Testably.Abstractions.Testing.Tests/Statistics/FileSystem/FileStreamFactoryStatisticsTests.cs
Tests/Testably.Abstractions.Testing.Tests/Statistics/FileSystem/FileStreamStatisticsTests.cs
Tests/Testably.Abstractions.Testing.Tests/Statistics/FileSystem/FileSystemWatcherFactoryStatisticsTests.cs
Tests/Testably.Abstractions.Testing.Tests/Statistics/FileSystem/FileSystemWatcherStatisticsTests.cs
Tests/Testably.Abstractions.Testing.Tests/Statistics/MethodStatisticsTests.cs
Tests/Testably.Abstractions.Testing.Tests/Statistics/ParameterDescriptionTests.cs
Tests/Testably.Abstractions.Testing.Tests/Statistics/StatisticsTests.cs

Fix the errors from the [sonar cloud static code analysis](https://github.com/Testably/Testably.Abstractions/runs/22481531017).

fix: errors from static code analysis

---

Source/Testably.Abstractions.Testing/Statistics/CallStatistics.cs
Source/Testably.Abstractions.Testing/Statistics/IStatistics.cs
Source/Testably.Abstractions.Testing/Statistics/MethodStatistic.cs
Tests/Testably.Abstractions.Testing.Tests/Statistics/FileSystem/FileStreamStatisticsTests.cs
Tests/Testably.Abstractions.Testing.Tests/Statistics/MethodStatisticsTests.cs
Tests/Testably.Abstractions.Testing.Tests/Statistics/StatisticsTests.cs
Tests/Testably.Abstractions.Testing.Tests/TestHelpers/StatisticsTestHelpers.cs

The global counter should not be treated as an index!
Therefore replace the dictionary in the statistics with an array and move the counter information into the `MethodStatistic` itself.

refactor: replace the dictionary in the statistics with an array

---

README.md

As mentioned in #471 improve the initialization examples in the README and replace "productive code" with "production code".

docs: improve readme examples

---

renovate.json

Limit renovate to [earlyMondays](https://docs.renovatebot.com/presets-schedule/#scheduleearlymondays).
This affects #236

chore: Limit "renovate" to run only weekly

---

.github/workflows/build.yml
.github/workflows/ci.yml

With #479 a `global.json` was added, but it now fails the build, because the code coverage upload task acn no longer be executed.

fix: Install .NET on code upload step

---

Source/Testably.Abstractions.Compression/ZipArchiveWrapper.cs
Source/Testably.Abstractions.Testing/FileSystem/DirectoryInfoMock.cs
Source/Testably.Abstractions.Testing/FileSystem/FileSystemWatcherMock.cs
Source/Testably.Abstractions.Testing/Notification.cs
Source/Testably.Abstractions/FileSystem/FileSystemWatcherWrapper.cs
Source/Testably.Abstractions/TimeSystem/TimerWrapper.cs
Testably.Abstractions.sln.DotSettings
Tests/Helpers/Testably.Abstractions.Tests.SourceGenerator/ClassGeneratorBase.cs
Tests/Testably.Abstractions.Testing.Tests/FileSystem/ChangeHandlerTests.cs
Tests/Testably.Abstractions.Testing.Tests/RandomProvider.GeneratorTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/File/TestDataGetEncodingDifference.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileSystemWatcher/Tests.cs

Adapt ReSharper File Layout to avoid Sonar issues due to method overloads that are not adjacent.

refactor: adapt ReSharper File Layout to avoid Sonar issues during cleanup

---

Source/Testably.Abstractions.Testing/Helpers/CharExtensionMethods.cs
Source/Testably.Abstractions.Testing/Statistics/CallStatistics.cs
Source/Testably.Abstractions.Testing/Statistics/FileSystemStatistics.cs
Source/Testably.Abstractions.Testing/Statistics/PathStatistics.cs
Tests/Testably.Abstractions.Testing.Tests/Helpers/CharExtensionMethodsTests.cs
Tests/Testably.Abstractions.Testing.Tests/Statistics/FileSystem/DirectoryInfoFactoryStatisticsTests.cs
Tests/Testably.Abstractions.Testing.Tests/Statistics/FileSystem/DirectoryInfoStatisticsTests.cs
Tests/Testably.Abstractions.Testing.Tests/Statistics/FileSystem/DirectoryStatisticsTests.cs
Tests/Testably.Abstractions.Testing.Tests/Statistics/FileSystem/DriveInfoFactoryStatisticsTests.cs
Tests/Testably.Abstractions.Testing.Tests/Statistics/FileSystem/DriveInfoStatisticsTests.cs
Tests/Testably.Abstractions.Testing.Tests/Statistics/FileSystem/FileInfoFactoryStatisticsTests.cs
Tests/Testably.Abstractions.Testing.Tests/Statistics/FileSystem/FileInfoStatisticsTests.cs
Tests/Testably.Abstractions.Testing.Tests/Statistics/FileSystem/FileStatisticsTests.cs
Tests/Testably.Abstractions.Testing.Tests/Statistics/FileSystem/FileStreamFactoryStatisticsTests.cs
Tests/Testably.Abstractions.Testing.Tests/Statistics/FileSystem/FileStreamStatisticsTests.cs
Tests/Testably.Abstractions.Testing.Tests/Statistics/FileSystem/FileSystemWatcherFactoryStatisticsTests.cs
Tests/Testably.Abstractions.Testing.Tests/Statistics/FileSystem/FileSystemWatcherStatisticsTests.cs
Tests/Testably.Abstractions.Testing.Tests/Statistics/FileSystem/PathStatisticsTests.cs
Tests/Testably.Abstractions.Testing.Tests/Statistics/MethodStatisticsTests.cs
Tests/Testably.Abstractions.Testing.Tests/Statistics/PathStatisticsTests.cs
Tests/Testably.Abstractions.Testing.Tests/Statistics/PropertyStatisticsTests.cs
Tests/Testably.Abstractions.Testing.Tests/Statistics/StatisticsTests.cs

The statistics key was sometimes not correct (e.g. when mixing absolute and relative paths).

fix: correctly match statistic paths

---

Source/Testably.Abstractions.Testing/FileSystemInitializerExtensions.cs
Source/Testably.Abstractions.Testing/Helpers/Execute.cs
Source/Testably.Abstractions.Testing/Helpers/ExecuteExtensions.cs
Tests/Testably.Abstractions.Testing.Tests/Helpers/ExecuteExtensionsTests.cs
Tests/Testably.Abstractions.Testing.Tests/Helpers/ExecuteTests.cs

This enables testing of the OS dependent methods.

refactor: extract extension methods from `Execute`

---

Source/Testably.Abstractions.Interface/Helpers/PathSystemBase.cs
Source/Testably.Abstractions.Testing/FileSystem/DirectoryInfoFactoryMock.cs
Source/Testably.Abstractions.Testing/FileSystem/DriveInfoFactoryMock.cs
Source/Testably.Abstractions.Testing/FileSystem/FileInfoFactoryMock.cs
Source/Testably.Abstractions.Testing/FileSystem/FileStreamFactoryMock.cs
Source/Testably.Abstractions.Testing/FileSystem/FileSystemWatcherFactoryMock.cs
Source/Testably.Abstractions.Testing/FileSystem/PathMock.cs
Source/Testably.Abstractions/FileSystem/DirectoryInfoFactory.cs
Source/Testably.Abstractions/FileSystem/DriveInfoFactory.cs
Source/Testably.Abstractions/FileSystem/FileInfoFactory.cs
Source/Testably.Abstractions/FileSystem/FileStreamFactory.cs
Source/Testably.Abstractions/FileSystem/FileSystemWatcherFactory.cs
Source/Testably.Abstractions/FileSystem/PathWrapper.cs
Tests/Api/Testably.Abstractions.Api.Tests/Expected/Testably.Abstractions.Interface_net6.0.txt
Tests/Api/Testably.Abstractions.Api.Tests/Expected/Testably.Abstractions.Interface_net7.0.txt
Tests/Api/Testably.Abstractions.Api.Tests/Expected/Testably.Abstractions.Interface_net8.0.txt
Tests/Api/Testably.Abstractions.Api.Tests/Expected/Testably.Abstractions.Interface_netstandard2.0.txt
Tests/Api/Testably.Abstractions.Api.Tests/Expected/Testably.Abstractions.Interface_netstandard2.1.txt

Exclude obsolete methods and classes from code coverage.

refactor: exclude obsolete methods from code coverage

---

Directory.Packages.props
Source/Testably.Abstractions.Testing/FileSystemInitializer/DirectoryCleaner.cs
Tests/Helpers/Testably.Abstractions.TestHelpers/FileSystemTestBase.cs
Tests/Helpers/Testably.Abstractions.TestHelpers/Settings/RealFileSystemFixture.cs
Tests/Helpers/Testably.Abstractions.TestHelpers/Settings/TestEnvironment.cs
Tests/Helpers/Testably.Abstractions.TestHelpers/Settings/TestSettingsFixture.cs
Tests/Helpers/Testably.Abstractions.TestHelpers/Test.cs
Tests/Helpers/Testably.Abstractions.TestHelpers/TimeSystemTestBase.cs
Tests/Helpers/Testably.Abstractions.Tests.SourceGenerator/ClassGenerators/FileSystemClassGenerator.cs
Tests/Helpers/Testably.Abstractions.Tests.SourceGenerator/ClassGenerators/TimeSystemClassGenerator.cs
Tests/Helpers/Testably.Abstractions.Tests.SourceGenerator/GlobalGenerator.cs
Tests/Settings/Testably.Abstractions.TestSettings/BrittleTests.cs
Tests/Settings/Testably.Abstractions.TestSettings/Helper.cs
Tests/Settings/Testably.Abstractions.TestSettings/RealFileSystemTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileStream/DisposeTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileStream/ReadTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileStream/Tests.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileStream/WriteTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileSystemWatcher/IncludeSubdirectoriesTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileSystemWatcher/Tests.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileSystemWatcher/WaitForChangedTests.cs
Tests/Testably.Abstractions.Tests/TimeSystem/TimerTests.cs

Some tests are marked as brittle. These should be skippable via test settings.

feat: enable/disable brittle tests via test settings

---

.github/workflows/ci.yml

Currently the .NET Framework tests don't implement the retry-policy which results in sometimes failing tests (e.g. https://github.com/Testably/Testably.Abstractions/actions/runs/8352478169/job/22862628346?pr=516)

feat: add retry also to .NET Framework tests

---

Tests/Testably.Abstractions.Testing.Tests/Statistics/StatisticsTests.Helpers.cs

`Nullable` is declared both in Testable.Abstractions.Testing and Testable.Abstractions.Testing.Tests. As internals are visible to the test project, this project has conflicting declarations of the `NotNullWhenAttribute` resulting in the following build warning `warning CS0436: The type 'NotNullWhenAttribute' in '...\net40\Nullable\NotNullWhenAttribute.cs' conflicts with the imported type 'NotNullWhenAttribute' in 'Testably.Abstractions.Testing, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null'. Using the type defined in '...\net40\Nullable\NotNullWhenAttribute.cs'.`
Disable this build warning, as the Nullable package is identical in both projects.

fix: disable build warning CS0436 in `Testably.Abstractions.Testing.Tests`

---

Tests/Directory.Build.props
Tests/Testably.Abstractions.Testing.Tests/NotificationTests.cs
Tests/Testably.Abstractions.Testing.Tests/Statistics/FileSystem/FileSystemWatcherStatisticsTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/File/AppendAllLinesAsyncTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/File/AppendAllTextAsyncTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/File/OpenReadTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/File/ReadLinesAsyncTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/File/WriteAllBytesAsyncTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/File/WriteAllLinesAsyncTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/File/WriteAllTextAsyncTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileStream/ReadTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileStream/Tests.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileStream/WriteTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileSystemWatcher/EventTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileSystemWatcher/Tests.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileSystemWatcher/WaitForChangedTests.cs
Tests/Testably.Abstractions.Tests/TimeSystem/TaskTests.cs
Tests/Testably.Abstractions.Tests/TimeSystem/TimerTests.cs

Avoid calls to `.ConfigureAwait(false)` as specified in [xUnit1030](https://xunit.net/xunit.analyzers/rules/xUnit1030)

refactor: remove `.ConfigureAwait` in tests

---

Source/Testably.Abstractions.Testing/Notification.cs
Source/Testably.Abstractions.Testing/TimeSystem/TimerMock.cs
Tests/Testably.Abstractions.Testing.Tests/FileSystem/FileSystemWatcherMockTests.cs
Tests/Testably.Abstractions.Testing.Tests/NotificationTests.cs
Tests/Testably.Abstractions.Testing.Tests/TimeSystem/TimerFactoryMockTests.cs
Tests/Testably.Abstractions.Testing.Tests/TimeSystem/TimerMockTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileStream/ReadTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileStream/WriteTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileSystemWatcher/EnableRaisingEventsTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileSystemWatcher/EventTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileSystemWatcher/FilterTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileSystemWatcher/IncludeSubdirectoriesTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileSystemWatcher/NotifyFiltersTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileSystemWatcher/Tests.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileSystemWatcher/WaitForChangedTests.cs
Tests/Testably.Abstractions.Tests/TimeSystem/TimerFactoryTests.cs
Tests/Testably.Abstractions.Tests/TimeSystem/TimerTests.cs

- Dispose `ManualResetEventSlim`

refactor: dispose of `ManualResetEventSlim`

---

Source/Testably.Abstractions.Testing/FileSystem/FileStreamMock.cs
Tests/Testably.Abstractions.Tests/FileSystem/Directory/CreateDirectoryTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/Directory/DeleteTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/Directory/MoveTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/Directory/Tests.AdjustTimes.cs
Tests/Testably.Abstractions.Tests/FileSystem/Directory/Tests.Times.cs
Tests/Testably.Abstractions.Tests/FileSystem/File/AppendAllTextTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/File/CopyTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/File/MoveTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/File/OpenTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/File/ReadAllBytesTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/File/ReadAllTextTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/File/SetAttributesTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/File/Tests.cs
Tests/Testably.Abstractions.Tests/FileSystem/File/WriteAllTextTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileStream/AdjustTimesTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileStream/DisposeTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileStream/ReadTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileStream/Tests.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileStream/WriteTests.cs
Tests/Testably.Abstractions.Tests/TestHelpers/TimeTestHelper.cs
Tests/Testably.Abstractions.Tests/TimeSystem/DateTimeTests.cs
Tests/Testably.Abstractions.Tests/TimeSystem/TaskTests.cs
Tests/Testably.Abstractions.Tests/TimeSystem/ThreadTests.cs

Fix incorrect adjustment of the LastAccessTime in `FileStream.EndRead` and activate the skipped brittle tests.
Refactor assertions for `DateTime` between two times by adding an extension method `BeBetween` which checks for the time being between start and end and applying the system clock tolerance on both values.
*Note: The test keeps failing arbitrarily on MacOS, as the LastAccessTime is sometimes adjusted, so the test remains skipped on MacOS*

fix: do not adjust LastAccessTime in `FileStream.EndRead`

---

Tests/Testably.Abstractions.Compression.Tests/ZipFile/ExtractToDirectoryTests.cs
Tests/Testably.Abstractions.Testing.Tests/FileSystem/FileMockTests.cs
Tests/Testably.Abstractions.Testing.Tests/Statistics/MethodStatisticsTests.cs
Tests/Testably.Abstractions.Testing.Tests/Statistics/ParameterDescriptionTests.cs
Tests/Testably.Abstractions.Testing.Tests/Statistics/PropertyStatisticsTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/Path/Tests.cs

- Add missing tests for `ZipFile.ExtractToDirectory`
- Add test for initializaltion of statistic counter
- Add missing tests for `ParameterDescription`
- Add missing test for `Path.GetInvalidPathChars`
- Add test for correct exception when calling `GetUnixFileMode` on windows
- Add test for correct exception when accessing a missing file via a `SafeFileHandle`

coverage: add missing tests

---

.github/workflows/build.yml

Exclude .NET Framework coverage report from the generated coverage report sent to Codacy.

fix: Report Generator does not support mixing .NET Framework and .NET Core

---

.github/workflows/ci-stryker.yml

Enable a stryker CI-Build with the [`since`-Flag](https://stryker-mutator.io/docs/stryker-net/configuration/#since-flag-committish) and write a corresponding comment with the Stryker Dashboard Badge to the pull request.

feat: Enable Stryker CI-Build

---

Source/Testably.Abstractions.Testing/Helpers/EnumerationOptionsHelper.cs
Source/Testably.Abstractions.Testing/Storage/InMemoryStorage.cs
Tests/Testably.Abstractions.Tests/FileSystem/Directory/EnumerateFilesTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/Directory/GetFilesTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/DirectoryInfo/EnumerateFilesTests.cs

Support the mentioned formats in https://github.com/TestableIO/System.IO.Abstractions/issues/596, especially the following:
> Another pattern that works in the real filesystem and not on the MockFileSystem is `"someDirectory\\*.txt"`, this includes `".\\*.txt"`

fix: support search pattern with subdirectories when enumerating a directory

---

.github/workflows/release.yml

The release build fails with the following error:
> [Invalid workflow file: .github/workflows/release.yml#L228](https://github.com/Testably/Testably.Abstractions/actions/runs/8469291223/workflow)
The workflow is not valid. .github/workflows/release.yml (Line: 228, Col: 13): Job 'deploy' depends on unknown job 'analyze'. .github/workflows/release.yml (Line: 286, Col: 13): Job 'cleanup' depends on job 'deploy' which creates a cycle in the dependency graph.

fix: dependency error in release.yml

---

Tests/Testably.Abstractions.Tests/FileSystem/FileStream/ReadTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileStream/WriteTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileSystemWatcher/EnableRaisingEventsTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileSystemWatcher/EventTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileSystemWatcher/FilterTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileSystemWatcher/IncludeSubdirectoriesTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileSystemWatcher/NotifyFiltersTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileSystemWatcher/Tests.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileSystemWatcher/WaitForChangedTests.cs
Tests/Testably.Abstractions.Tests/TimeSystem/TimerTests.cs

Test run sporadically fails on Ubuntu without failing test:
> The active test run was aborted. Reason: Test host process crashed : Unhandled exception. System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Threading.ManualResetEventSlim'.
at System.Threading.ManualResetEventSlim.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
at System.Threading.ManualResetEventSlim.Wait(Int32 millisecondsTimeout)
at Testably.Abstractions.Tests.TimeSystem.TimerTests`1.<>c__DisplayClass10_0.<<Change_WithLong_ShouldResetTimer>b__0>d.MoveNext() in /home/runner/work/Testably.Abstractions/Testably.Abstractions/Tests/Testably.Abstractions.Tests/TimeSystem/TimerTests.cs:line 221
--- End of stack trace from previous location ---
at …

fix: catch `ObjectDisposedException` in tests

---

.github/workflows/release.yml

Skip `state: released` flagged issues and prs in the [apexskier/github-release-commenter](https://github.com/apexskier/github-release-commenter) action in the release build pipeline.
This is a workaround for a [known limitation](https://github.com/apexskier/github-release-commenter?tab=readme-ov-file#known-limitations) to allow re-triggering the build.

fix: skip `state: released` flagged issues and PRs during release commenting

---

.github/workflows/build.yml

The Sonarcloud badge displays a "Project not found" error in the [release README](https://www.nuget.org/packages/Testably.Abstractions/3.0.0#readme-body-tab), because the release branches are no longer explicitely tracked:
Remove both codacy and sonarcloud badges from release README, as they are not aligned to the release version.

fix: remove the sonarcloud badge from the release README

---

Source/Testably.Abstractions.Testing/Statistics/CallStatistics.cs
Source/Testably.Abstractions.Testing/Statistics/FileSystemStatistics.cs
Source/Testably.Abstractions.Testing/Statistics/IFileSystemStatistics.cs
Source/Testably.Abstractions.Testing/Statistics/IPathStatistics.cs
Source/Testably.Abstractions.Testing/Statistics/IStatistics.cs
Source/Testably.Abstractions.Testing/Statistics/PathStatistics.cs
Tests/Api/Testably.Abstractions.Api.Tests/Expected/Testably.Abstractions.Testing_net6.0.txt
Tests/Api/Testably.Abstractions.Api.Tests/Expected/Testably.Abstractions.Testing_net7.0.txt
Tests/Api/Testably.Abstractions.Api.Tests/Expected/Testably.Abstractions.Testing_net8.0.txt
Tests/Api/Testably.Abstractions.Api.Tests/Expected/Testably.Abstractions.Testing_netstandard2.0.txt
Tests/Api/Testably.Abstractions.Api.Tests/Expected/Testably.Abstractions.Testing_netstandard2.1.txt
Tests/Testably.Abstractions.Testing.Tests/Statistics/FileSystem/DirectoryInfoFactoryStatisticsTests.cs
Tests/Testably.Abstractions.Testing.Tests/Statistics/FileSystem/DriveInfoFactoryStatisticsTests.cs
Tests/Testably.Abstractions.Testing.Tests/Statistics/FileSystem/FileInfoFactoryStatisticsTests.cs
Tests/Testably.Abstractions.Testing.Tests/Statistics/FileSystem/FileStreamFactoryStatisticsTests.cs
Tests/Testably.Abstractions.Testing.Tests/Statistics/FileSystem/FileSystemWatcherFactoryStatisticsTests.cs
Tests/Testably.Abstractions.Testing.Tests/Statistics/PathStatisticsTests.cs

In order to know the type stored in a statistic, the interfaces should be generic and provide details about the information stored in them.
This is the last step that fixes #476 .

feat: make statistic interfaces generic

---

Source/Testably.Abstractions.Testing/FileSystemInitializerExtensions.cs
Source/Testably.Abstractions.Testing/Helpers/AssemblyNameExtensions.cs
Source/Testably.Abstractions.Testing/Helpers/FileSystemExtensions.cs
Source/Testably.Abstractions.Testing/Initializer/FileSystemInitializer.cs
Source/Testably.Abstractions.Testing/MockFileSystem.cs
Source/Testably.Abstractions.Testing/RandomSystem/RandomMock.cs
Source/Testably.Abstractions.Testing/Storage/IStorage.cs
Source/Testably.Abstractions.Testing/Storage/InMemoryStorage.cs
Tests/Testably.Abstractions.Testing.Tests/Helpers/AssemblyNameExtensionsTests.cs
Tests/Testably.Abstractions.Testing.Tests/Helpers/FileSystemExtensionsTests.cs
Tests/Testably.Abstractions.Testing.Tests/MockFileSystemInitializationTests.cs
Tests/Testably.Abstractions.Testing.Tests/NotificationTests.cs
Tests/Testably.Abstractions.Testing.Tests/Storage/InMemoryStorageTests.cs
Tests/Testably.Abstractions.Tests/RandomSystem/RandomTests.cs
Tests/Testably.Abstractions.Tests/TimeSystem/TimerTests.cs

Refactor some implementation details, to catch uncaught errors (see Stryker.NET):
- Allow `null` in `IStorage.GetOrAddDrive` to simplify the implementation
- Add tests for `Notification.ExecuteWhileWaiting`
- Extract getting the name for an `AssemblyName` to an extension method to allow testing it
- Avoid including the default value for `int` in the choices in the random tests
- Extract getting a shared `IRandom` instance from the `IFileSystem` to an extension method to allow testing it
- Fix the test for changing a disposed timer in .NET 8 or greater (it returns false instead of throwing an `ObjectDisposedException`)

refactor: improve mutation score

---

.github/workflows/ci.yml
Source/Testably.Abstractions.AccessControl/AccessControlHelpers.cs
Source/Testably.Abstractions.AccessControl/DirectoryAclExtensions.cs
Source/Testably.Abstractions.AccessControl/DirectoryInfoAclExtensions.cs
Tests/Testably.Abstractions.AccessControl.Tests/DirectoryAclExtensionsTests.cs
Tests/Testably.Abstractions.AccessControl.Tests/DirectoryInfoAclExtensionsTests.cs
Tests/Testably.Abstractions.AccessControl.Tests/ExceptionMissingFileTests.cs
Tests/Testably.Abstractions.AccessControl.Tests/FileAclExtensionsTests.cs
Tests/Testably.Abstractions.AccessControl.Tests/FileInfoAclExtensionsTests.cs

Add tests for missing cases in AccessControl extensions, detected by Stryker.NET.

refactor: improve mutation score for AccessControl extensions

---

Source/Testably.Abstractions.Testing/Storage/InMemoryStorage.cs
Tests/Testably.Abstractions.Tests/FileSystem/File/CopyTests.cs

fix: copying a file throws if a file handle with `ReadWrite` share is open

---

Source/Testably.Abstractions.Testing/Storage/IStorageContainer.cs
Source/Testably.Abstractions.Testing/Storage/InMemoryContainer.cs
Source/Testably.Abstractions.Testing/Storage/InMemoryStorage.cs
Source/Testably.Abstractions.Testing/Storage/NullContainer.cs
Tests/Testably.Abstractions.Testing.Tests/TestHelpers/LockableContainer.cs
Tests/Testably.Abstractions.Tests/FileSystem/File/CopyTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/File/MoveTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/File/ReplaceTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileInfo/CopyToTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileInfo/MoveToTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileInfo/ReplaceTests.cs

Ignore FileShare for `Move` and `Replace` methods on Linux or MacOS.
*See https://github.com/dotnet/runtime/issues/52700 for more details.*
Add tests to verify the correct behavior for the following methods while an open file handle exists:
- `File.Copy`
- `File.Move`
- `File.Replace`
- `FileInfo.CopyTo`
- `FileInfo.MoveTo`
- `FileInfo.Replace`

fix: ensure correct behavior when moving or replacing a file with an open handle

---

Source/Testably.Abstractions.Compression/Internal/ZipUtilities.cs
Tests/Testably.Abstractions.Compression.Tests/Internal/ExecuteTests.cs
Tests/Testably.Abstractions.Compression.Tests/Internal/ZipUtilitiesTests.cs
Tests/Testably.Abstractions.Compression.Tests/ZipFile/CreateFromDirectoryTests.cs
Tests/Testably.Abstractions.Compression.Tests/ZipFile/ExtractToDirectoryTests.cs

Add tests for missing cases in Compression extensions, detected by Stryker.NET.

refactor: improve mutation score for Compression extensions

---

.github/workflows/build.yml
README.md

Update the badge to Github builds on the release readme on nuget.org to include the branch information.

docs: improve links in nuget README

---

Source/Testably.Abstractions.Testing/FileSystemInitializerExtensions.cs
Source/Testably.Abstractions.Testing/Helpers/FileSystemExtensions.cs
Source/Testably.Abstractions.Testing/Helpers/PathHelper.cs
Source/Testably.Abstractions.Testing/Storage/StorageExtensions.cs
Tests/Testably.Abstractions.Tests/FileSystem/Directory/DeleteTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/Directory/EnumerateDirectoriesTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/Directory/EnumerateFileSystemInfosTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/Directory/EnumerateFilesTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/Directory/GetDirectoriesTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/Directory/GetFileSystemInfosTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/Directory/GetFilesTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/Directory/ResolveLinkTargetTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/Directory/SearchFilterTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/DirectoryInfo/CreateTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/DirectoryInfoFactory/Tests.cs
Tests/Testably.Abstractions.Tests/FileSystem/File/ResolveLinkTargetTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileInfo/ExistsTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/Path/ChangeExtensionTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/Path/CombineTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/Path/GetDirectoryNameTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/Path/GetFullPathTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/Path/JoinTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/Path/Tests.cs

In order to simulate a FileSystem on other platforms (see #460) we should avoid using System.IO calls in the MockFileSystem and its tests.

fix: avoid using methods from System.IO in Testing

---

Source/Testably.Abstractions.Testing/Helpers/Execute.MacPath.cs
Source/Testably.Abstractions.Testing/Helpers/Execute.WindowsPath.cs
Source/Testably.Abstractions.Testing/Testably.Abstractions.Testing.csproj
Tests/Api/Testably.Abstractions.Api.Tests/Expected/Testably.Abstractions.Testing_net6.0.txt
Tests/Api/Testably.Abstractions.Api.Tests/Expected/Testably.Abstractions.Testing_net7.0.txt
Tests/Api/Testably.Abstractions.Api.Tests/Expected/Testably.Abstractions.Testing_net8.0.txt
Tests/Api/Testably.Abstractions.Api.Tests/Expected/Testably.Abstractions.Testing_netstandard2.0.txt
Tests/Api/Testably.Abstractions.Api.Tests/Expected/Testably.Abstractions.Testing_netstandard2.1.txt
Tests/Helpers/Testably.Abstractions.TestHelpers/Test.cs
Tests/Helpers/Testably.Abstractions.Tests.SourceGenerator/ClassGenerators/FileSystemClassGenerator.cs
Tests/Testably.Abstractions.Tests/FileSystem/Directory/SearchFilterTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/Path/GetPathRootTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/Path/GetTempPathTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/Path/IsPathRootedTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/Path/Tests.cs
Tests/Testably.Abstractions.Tests/TestHelpers/TestExtensions.cs
Tests/Testably.Abstractions.Tests/TestHelpers/TestOS.cs
Tests/Testably.Abstractions.Tests/TestHelpers/TestOSExtensions.cs

Create the foundation for writing simulated tests and enable the tests for the properties and methods implemented in #564 
*See #460*

feat: foundation for simulated tests

---

Source/Testably.Abstractions.Testing/Helpers/Execute.SimulatedPath.cs
Tests/Helpers/Testably.Abstractions.Tests.SourceGenerator/ClassGenerators/FileSystemClassGenerator.cs
Tests/Testably.Abstractions.Tests/FileSystem/Path/JoinTests.cs

Implement the `Join` methods for `Path`.

feat: implement `Join` for simulated `Path `

---

Source/Testably.Abstractions.Testing/Helpers/Execute.SimulatedPath.cs
Tests/Helpers/Testably.Abstractions.Tests.SourceGenerator/ClassGenerators/FileSystemClassGenerator.cs
Tests/Testably.Abstractions.Tests/FileSystem/Path/TryJoinTests.cs

Implement the `TryJoin` methods for `Path`.

feat: implement `TryJoin` for simulated `Path`

---

Source/Testably.Abstractions.Testing/Helpers/Execute.MacPath.cs
Source/Testably.Abstractions.Testing/Helpers/Execute.SimulatedPath.cs
Tests/Testably.Abstractions.Tests/FileSystem/Path/GetRandomFileNameTests.cs

Implement the `GetRandomFileName` methods for `Path`.

feat: implement `GetRandomFileName` for simulated `Path`

---

Source/Testably.Abstractions.Testing/Helpers/Execute.LinuxPath.cs
Source/Testably.Abstractions.Testing/Helpers/Execute.SimulatedPath.cs
Source/Testably.Abstractions.Testing/Helpers/Execute.WindowsPath.cs
Tests/Helpers/Testably.Abstractions.Tests.SourceGenerator/ClassGenerators/FileSystemClassGenerator.cs
Tests/Testably.Abstractions.Tests/FileSystem/Path/GetDirectoryNameTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/Path/IsPathRootedTests.cs
Tests/Testably.Abstractions.Tests/TestHelpers/TestExtensions.cs

Implement the `GetDirectoryName` methods for `Path`.

feat: implement `GetDirectoryName` for simulated `Path`

---

Source/Testably.Abstractions.Testing/Helpers/Execute.SimulatedPath.cs
Tests/Helpers/Testably.Abstractions.Tests.SourceGenerator/ClassGenerators/FileSystemClassGenerator.cs
Tests/Testably.Abstractions.Tests/FileSystem/Path/CombineTests.cs

Implement the `Combine` methods for `Path`.
*See #460*

feat: implement `Combine` for simulated `Path`

---

Source/Testably.Abstractions.Testing/Helpers/Execute.SimulatedPath.cs
Tests/Helpers/Testably.Abstractions.Tests.SourceGenerator/ClassGenerators/FileSystemClassGenerator.cs
Tests/Testably.Abstractions.Tests/FileSystem/Path/HasExtensionTests.cs

Implement the `HasExtension` and `TrimEndingDirectorySeparator` methods for `Path`.
*See #460*

feat: implement `HasExtension` and `TrimEndingDirectorySeparator` for simulated `Path`

---

Source/Testably.Abstractions.Testing/Helpers/Execute.MacPath.cs
Source/Testably.Abstractions.Testing/Helpers/Execute.NativePath.cs
Source/Testably.Abstractions.Testing/Helpers/Execute.SimulatedPath.cs
Source/Testably.Abstractions.Testing/Helpers/Execute.cs
Source/Testably.Abstractions.Testing/MockFileSystem.cs
Source/Testably.Abstractions.Testing/MockRandomSystem.cs
Tests/Api/Testably.Abstractions.Api.Tests/Expected/Testably.Abstractions.Testing_net6.0.txt
Tests/Api/Testably.Abstractions.Api.Tests/Expected/Testably.Abstractions.Testing_net7.0.txt
Tests/Api/Testably.Abstractions.Api.Tests/Expected/Testably.Abstractions.Testing_net8.0.txt
Tests/Api/Testably.Abstractions.Api.Tests/Expected/Testably.Abstractions.Testing_netstandard2.0.txt
Tests/Api/Testably.Abstractions.Api.Tests/Expected/Testably.Abstractions.Testing_netstandard2.1.txt
Tests/Helpers/Testably.Abstractions.Tests.SourceGenerator/ClassGenerators/FileSystemClassGenerator.cs
Tests/Testably.Abstractions.Testing.Tests/FileSystem/PathMockTests.cs
Tests/Testably.Abstractions.Testing.Tests/MockFileSystemInitializationTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/Path/GetTempFileNameTests.cs

Implement the `GetTempFileName` methods for `Path` and allow initialization with `IRandomProvider` to test random edge cases.
*See #460*

feat: implement `GetTempFileName` for simulated `Path`

---

Source/Testably.Abstractions.Testing/Helpers/Execute.SimulatedPath.cs
Tests/Helpers/Testably.Abstractions.Tests.SourceGenerator/ClassGenerators/FileSystemClassGenerator.cs
Tests/Testably.Abstractions.Tests/FileSystem/Path/GetRelativePathTests.cs

Implement the `GetRelativePath` methods for `Path`.
*See #460*

feat: implement `GetRelativePath` for simulated `Path`

---

Source/Testably.Abstractions.Testing/TimeSystem/DateTimeMock.cs

Correctly use local time for calculating `DateTime.Today` in `DateTimeMock`

fix: use local time for Today in `DateTimeMock`

---

Source/Testably.Abstractions.Testing/FileSystem/FileSystemWatcherMock.cs
Tests/Testably.Abstractions.Testing.Tests/FileSystem/FileSystemWatcherMockTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileSystemWatcher/EnableRaisingEventsTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileSystemWatcher/EventTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileSystemWatcher/FilterTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileSystemWatcher/IncludeSubdirectoriesTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileSystemWatcher/NotifyFiltersTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileSystemWatcher/Tests.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileSystemWatcher/WaitForChangedTests.cs

The [FileSystemEventArgs](https://github.com/dotnet/runtime/blob/v8.0.4/src/libraries/System.IO.FileSystem.Watcher/src/System/IO/FileSystemEventArgs.cs) implicitly combines the path in `FullPath` from its constructor arguments. When the file system is simulated, the directory separator char is incorrect.
When using the simulation mode, use reflection to correctly set the underlying backing field.

fix: correctly set simulated EventArgs in `FileSystemWatcherMock`

---

Source/Testably.Abstractions.Testing/Helpers/PathHelper.cs
Tests/Testably.Abstractions.Tests/FileSystem/File/CopyTests.cs

When providing an invalid path (e.g. `C::/foo`) the thrown exception should be an `IOException` with message "The filename, directory name, or volume label syntax is incorrect" and not a `DirectoryNotFoundException`.

fix: throw correct exception in File.Copy when using an invalid path

---

Feature.Flags.props
README.md
Source/Testably.Abstractions.Testing/Helpers/Execute.cs
Source/Testably.Abstractions.Testing/MockFileSystem.cs
Source/Testably.Abstractions.Testing/Testably.Abstractions.Testing.csproj
Tests/Api/Testably.Abstractions.Api.Tests/Expected/Testably.Abstractions.Testing_net6.0.txt
Tests/Api/Testably.Abstractions.Api.Tests/Expected/Testably.Abstractions.Testing_net7.0.txt
Tests/Api/Testably.Abstractions.Api.Tests/Expected/Testably.Abstractions.Testing_net8.0.txt
Tests/Api/Testably.Abstractions.Api.Tests/Expected/Testably.Abstractions.Testing_netstandard2.0.txt
Tests/Api/Testably.Abstractions.Api.Tests/Expected/Testably.Abstractions.Testing_netstandard2.1.txt
Tests/Helpers/Testably.Abstractions.Tests.SourceGenerator/ClassGenerators/FileSystemClassGenerator.cs
Tests/Testably.Abstractions.Testing.Tests/FileSystem/PathMockTests.cs
Tests/Testably.Abstractions.Testing.Tests/Helpers/ExecuteExtensionsTests.cs
Tests/Testably.Abstractions.Testing.Tests/Helpers/ExecuteTests.cs
Tests/Testably.Abstractions.Testing.Tests/Helpers/PathHelperTests.cs
Tests/Testably.Abstractions.Testing.Tests/MockFileSystemInitializationTests.cs
Tests/Testably.Abstractions.Testing.Tests/MockFileSystemTests.cs

Enable the simulation tests for all shared tests and make the simulation mode functionality public.
With this mode, it is possible to simulate the file system on another operating system, e.g. you can simulate a Linux file system on a Windows machine or vice versa.
The mode can be enabled in the constructor:
```
var fileSystem = new MockFileSystem(o => o.SimulatingOperatingSystem(SimulationMode.Linux));
```
**Limitation:**
The simulation mode currently only works on .NET (Core) and throw a `NotSupportedException` in the constructor, when setting it on .NET Framework.
*This fixes #460.*

feat: allow simulating other operating systems

---

Feature.Flags.props
Source/Testably.Abstractions.Testing/MockFileSystem.cs
Tests/Api/Testably.Abstractions.Api.Tests/Expected/Testably.Abstractions.Testing_netstandard2.0.txt
Tests/Api/Testably.Abstractions.Api.Tests/Expected/Testably.Abstractions.Testing_netstandard2.1.txt
Tests/Testably.Abstractions.Testing.Tests/FileSystem/PathMockTests.cs
Tests/Testably.Abstractions.Testing.Tests/MockFileSystemInitializationTests.cs
Tests/Testably.Abstractions.Testing.Tests/MockFileSystemTests.cs

Be more restrictive with the simulation mode and only enable it on .NET (6 or newer).
It is always possible to add it also to e.g. .NET Standard 2.1 without a breaking change, but removing it would be considered one.

refactor: disable simulation mode on .NET Standard

---

Source/Testably.Abstractions.Testing/MockFileSystem.cs
Tests/Api/Testably.Abstractions.Api.Tests/Expected/Testably.Abstractions.Testing_net6.0.txt
Tests/Api/Testably.Abstractions.Api.Tests/Expected/Testably.Abstractions.Testing_net7.0.txt
Tests/Api/Testably.Abstractions.Api.Tests/Expected/Testably.Abstractions.Testing_net8.0.txt
Tests/Api/Testably.Abstractions.Api.Tests/Expected/Testably.Abstractions.Testing_netstandard2.0.txt
Tests/Api/Testably.Abstractions.Api.Tests/Expected/Testably.Abstractions.Testing_netstandard2.1.txt
Tests/Testably.Abstractions.Testing.Tests/MockFileSystemInitializationTests.cs

Rename "Initialization" to "Options" in the constructor of `MockFileSystem` and replace `Action<MockFileSystemOptions>` with `Func<MockFileSystemOptions,MockFileSystemOptions>` to allow re-using a stored options class.

feat: rename "Initialization" to "Options"

---

Source/Testably.Abstractions.Testing/FileSystem/DirectoryMock.cs
Source/Testably.Abstractions.Testing/Helpers/FileSystemExtensions.cs
Source/Testably.Abstractions.Testing/Storage/InMemoryStorage.cs
Tests/Testably.Abstractions.Tests/FileSystem/Directory/EnumerateDirectoriesTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/Directory/EnumerateFilesTests.cs

Support the following properties of `EnumerationOptions`:
- MaxRecursionDepth
- ReturnSpecialDirectories
- AttributesToSkip
*This implements all attributes, except `IgnoreInaccessible` that are mentioned in https://github.com/TestableIO/System.IO.Abstractions/issues/653*

feat: support more properties of `EnumerationOptions`

---

Source/Testably.Abstractions.Testing/Storage/InMemoryStorage.cs
Tests/Testably.Abstractions.Tests/FileSystem/Directory/EnumerateDirectoriesTests.cs

Add support for the `IgnoreInaccessible` option of `EnumerationOptions`.
In order to simulate access errors in the `MockFileSystem`, specify the `IAccessControlStrategy`, e.g.:
```csharp
string inaccessiblePath = @"C:\Windows\System32\config";
mockFileSystem.WithAccessControlStrategy(
new DefaultAccessControlStrategy((p, _)
=> !p.Equals(inaccessiblePath)));
```
When trying to enumerate the inaccessible file or directory, the `MockFileSystem` will throw an `UnauthorizedAccessException`. If `EnumerationOptions.IgnoreInaccessible` is set to true, it will instead skip the inaccessible file or directory.
*After #589 this implements the remaining properties of `EnumerationOptions` that are mentioned in https://github.com/TestableIO/System.IO.Abstractions/issues/653*

feat: support remaining properties of `EnumerationOptions`

---

Source/Testably.Abstractions.Compression/Internal/ZipUtilities.cs
Source/Testably.Abstractions.Testing/Helpers/FileSystemExtensions.cs
Source/Testably.Abstractions.Testing/Polyfills/FileSystemName.cs
Source/Testably.Abstractions.Testing/Storage/InMemoryStorage.cs
Tests/Testably.Abstractions.Parity.Tests/Net48ParityTests.cs

Refactor the check, if items should be included in the enumeration depending on the `EnumerationOptions` into a separate method to reduce the overall complexity.

refactor: reduce method complexity in `InMemoryStorage`

---

Tests/Testably.Abstractions.Testing.Tests/NotificationTests.cs
Tests/Testably.Abstractions.Testing.Tests/Statistics/FileSystem/FileSystemWatcherStatisticsTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileStream/ReadTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileStream/WriteTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileSystemWatcher/EventTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileSystemWatcher/Tests.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileSystemWatcher/WaitForChangedTests.cs

- Avoid async methods in `Task.Run` in tests
- Make `FileStream.ReadTests` and `FileStream.WriteTests` part of the sequentially executed tests
- Set `EnableRaisingEvents` in `FileSystemWatcherStatisticsTests`

refactor: avoid blocking in tests

---

Tests/Testably.Abstractions.Testing.Tests/Statistics/FileSystem/FileStreamFactoryStatisticsTests.cs

In the `Method_Wrap_FileStream_ShouldRegisterCall` test, in order to get a valid `FileStream` a temporary test file has to be created on the real file system.
This file should be cleaned up after the test execution is finished.

refactor: cleanup temporary file created in unit test

---

Tests/Helpers/Testably.Abstractions.TestHelpers/FileSystemTestBase.cs
Tests/Helpers/Testably.Abstractions.TestHelpers/RandomSystemTestBase.cs
Tests/Helpers/Testably.Abstractions.TestHelpers/TestBase.cs
Tests/Helpers/Testably.Abstractions.TestHelpers/TimeSystemTestBase.cs
Tests/Testably.Abstractions.Tests/FileSystem/File/CopyTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileInfo/CopyToTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileStream/ReadTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileStream/WriteTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileSystemWatcher/EnableRaisingEventsTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileSystemWatcher/EventTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileSystemWatcher/FilterTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileSystemWatcher/IncludeSubdirectoriesTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileSystemWatcher/NotifyFiltersTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileSystemWatcher/Tests.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileSystemWatcher/WaitForChangedTests.cs
Tests/Testably.Abstractions.Tests/TimeSystem/TimerFactoryTests.cs
Tests/Testably.Abstractions.Tests/TimeSystem/TimerTests.cs

The `FileSystemWatcher.EventTests` sometimes fail, due to race-condition. Therefore make the following changes:
- Continually make the triggering changes in a background task, until the `CancellationToken` is cancelled at the end of the test
- Add and listen to separate triggers for when the triggering change was made and when the change was detected in the callback
- Make tests synchronous
- Add class `TestBase` with common timeout settings and use them throughout the Testably.Abstractions.Tests project.

refactor: fix brittle `EventTests`

---

Source/Testably.Abstractions.Testing/FileSystem/DirectoryInfoFactoryMock.cs
Source/Testably.Abstractions.Testing/FileSystem/DirectoryInfoMock.cs
Source/Testably.Abstractions.Testing/FileSystem/DirectoryMock.cs
Source/Testably.Abstractions.Testing/FileSystem/DriveInfoFactoryMock.cs
Source/Testably.Abstractions.Testing/FileSystem/DriveInfoMock.cs
Source/Testably.Abstractions.Testing/FileSystem/FileInfoFactoryMock.cs
Source/Testably.Abstractions.Testing/FileSystem/FileInfoMock.cs
Source/Testably.Abstractions.Testing/FileSystem/FileMock.cs
Source/Testably.Abstractions.Testing/FileSystem/FileStreamFactoryMock.cs
Source/Testably.Abstractions.Testing/FileSystem/FileStreamMock.cs
Source/Testably.Abstractions.Testing/FileSystem/FileSystemInfoMock.cs
Source/Testably.Abstractions.Testing/FileSystem/FileSystemWatcherFactoryMock.cs
Source/Testably.Abstractions.Testing/FileSystem/FileSystemWatcherMock.cs
Source/Testably.Abstractions.Testing/FileSystem/PathMock.cs
Source/Testably.Abstractions.Testing/Statistics/CallStatistics.cs
Source/Testably.Abstractions.Testing/Statistics/MethodStatistic.cs
Source/Testably.Abstractions.Testing/Statistics/PathStatistics.cs

Currently all calls during the initialization result in an initialized `ConcurrentDictionary` for each path. This PR changes the behaviour, that the entries of `PathStatistics` are only added, during a normal statistic registration.

refactor: reduce memory footprint of statistics functionality

---

Source/Testably.Abstractions.Testing/Helpers/FileSystemExtensions.cs
Source/Testably.Abstractions.Testing/Statistics/FileSystemStatistics.cs
Source/Testably.Abstractions.Testing/Statistics/PathStatistics.cs
Source/Testably.Abstractions.Testing/Storage/FileHandle.cs
Source/Testably.Abstractions.Testing/Storage/IStorage.cs
Source/Testably.Abstractions.Testing/Storage/InMemoryContainer.cs
Source/Testably.Abstractions.Testing/Storage/InMemoryStorage.cs

Store FileHandles centrally in `InMemoryStorage` instead of creating a separate `ConcurrentDictionary` for each file.
During initialization ignore the check for open file handles.

refactor: store file handles centrally in `InMemoryStorage`

---

Source/Testably.Abstractions.Testing/Helpers/FileSystemExtensions.cs
Source/Testably.Abstractions.Testing/Helpers/FileSystemRegistration.cs
Source/Testably.Abstractions.Testing/MockFileSystem.cs
Source/Testably.Abstractions.Testing/Statistics/FileSystemRegistration.cs
Source/Testably.Abstractions.Testing/Statistics/FileSystemStatistics.cs
Source/Testably.Abstractions.Testing/Statistics/IFileSystemStatistics.cs
Source/Testably.Abstractions.Testing/Storage/InMemoryContainer.cs
Tests/Api/Testably.Abstractions.Api.Tests/Expected/Testably.Abstractions.Testing_net6.0.txt
Tests/Api/Testably.Abstractions.Api.Tests/Expected/Testably.Abstractions.Testing_net7.0.txt
Tests/Api/Testably.Abstractions.Api.Tests/Expected/Testably.Abstractions.Testing_net8.0.txt
Tests/Api/Testably.Abstractions.Api.Tests/Expected/Testably.Abstractions.Testing_netstandard2.0.txt
Tests/Api/Testably.Abstractions.Api.Tests/Expected/Testably.Abstractions.Testing_netstandard2.1.txt
Tests/Testably.Abstractions.Testing.Tests/FileSystemInitializer/DirectoryCleanerTests.cs
Tests/Testably.Abstractions.Testing.Tests/FileSystemInitializer/FileSystemInitializerTests.cs
Tests/Testably.Abstractions.Testing.Tests/FileSystemInitializerExtensionsTests.cs
Tests/Testably.Abstractions.Testing.Tests/Statistics/FileSystem/DirectoryInfoFactoryStatisticsTests.cs
Tests/Testably.Abstractions.Testing.Tests/Statistics/FileSystem/DirectoryInfoStatisticsTests.cs
Tests/Testably.Abstractions.Testing.Tests/Statistics/FileSystem/DirectoryStatisticsTests.cs
Tests/Testably.Abstractions.Testing.Tests/Statistics/FileSystem/DriveInfoFactoryStatisticsTests.cs
Tests/Testably.Abstractions.Testing.Tests/Statistics/FileSystem/DriveInfoStatisticsTests.cs
Tests/Testably.Abstractions.Testing.Tests/Statistics/FileSystem/FileInfoFactoryStatisticsTests.cs
Tests/Testably.Abstractions.Testing.Tests/Statistics/FileSystem/FileInfoStatisticsTests.cs
Tests/Testably.Abstractions.Testing.Tests/Statistics/FileSystem/FileStatisticsTests.cs
Tests/Testably.Abstractions.Testing.Tests/Statistics/FileSystem/FileStreamFactoryStatisticsTests.cs
Tests/Testably.Abstractions.Testing.Tests/Statistics/FileSystem/FileStreamStatisticsTests.cs
Tests/Testably.Abstractions.Testing.Tests/Statistics/FileSystem/FileSystemWatcherFactoryStatisticsTests.cs
Tests/Testably.Abstractions.Testing.Tests/Statistics/FileSystem/FileSystemWatcherStatisticsTests.cs
Tests/Testably.Abstractions.Testing.Tests/Statistics/FileSystem/PathStatisticsTests.cs
Tests/Testably.Abstractions.Testing.Tests/Statistics/StatisticsTests.cs

Add a public property `TotalCount` to the statistics which contains the total number of registered statistic calls.

feat: Add `TotalCount` to Statistics

---

Source/Testably.Abstractions.Testing/FileSystem/FileStreamMock.cs
Source/Testably.Abstractions.Testing/Storage/IStorageContainer.cs
Source/Testably.Abstractions.Testing/Storage/InMemoryContainer.cs
Source/Testably.Abstractions.Testing/Storage/NullContainer.cs
Tests/Testably.Abstractions.Testing.Tests/TestHelpers/LockableContainer.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileStream/ReadTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileStream/Tests.cs

As reported in https://github.com/TestableIO/System.IO.Abstractions/issues/1131:
Update underlying memory stream, when the buffer in a shared `InMemoryContainer` changes.

fix: update buffer when accessing a `FileStream` in parallel

---

CONTRIBUTING.md

In order to easy contribution from other people, list the allowed prefixes for the conventional commits policy on the pull request title.

docs: Add allowed prefix for conventional commits

---

Source/Testably.Abstractions.Testing/Helpers/ExceptionFactory.cs
Source/Testably.Abstractions.Testing/Storage/InMemoryStorage.cs
Tests/Testably.Abstractions.Tests/FileSystem/Directory/MoveTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/File/CopyTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/File/MoveTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/File/ReplaceTests.cs

When calling `File.Replace` with source and destination only differing in casing, on MacOS the file system throws an exception that "Source and destination path must be different". Consider this case also in the `MockFileSystem`.
Also add tests for correct handling of case-only changes in `File.Move` and `File.Copy`.
*Note: This fix was inspired by https://github.com/TestableIO/System.IO.Abstractions/issues/1140 and https://github.com/TestableIO/System.IO.Abstractions/issues/1138.*

fix: Throw correct exception when using `File.Replace` with case-only changes on MacOS

---

Directory.Packages.props
Tests/Helpers/Testably.Abstractions.TestHelpers/AutoDomainDataAttribute.cs
Tests/Helpers/Testably.Abstractions.TestHelpers/IAutoDataCustomization.cs
Tests/Helpers/Testably.Abstractions.TestHelpers/Testably.Abstractions.TestHelpers.csproj
Tests/Testably.Abstractions.AccessControl.Tests/Internal/AccessControlHelperTests.cs
Tests/Testably.Abstractions.AccessControl.Tests/Testably.Abstractions.AccessControl.Tests.csproj

Add a custom `AutoDomainData` extension of [`AutoDataAttribute`](https://github.com/AutoFixture/AutoFixture/blob/master/Src/AutoFixture.xUnit2/AutoDataAttribute.cs), that uses [NSubstitute](https://nsubstitute.github.io) and allows for domain-specific [customizations](https://autofixture.github.io/docs/fixture-customization/).
In order to apply a customization for all tests in a project, add a class implementing the `IAutoDataCustomization` interface. This customization is then applied to all tests using the `[AutoDomainData]` attribute.
Additionally this attribute has a property `CustomizeWith` which can point to a class implementing the [`ICustomization`](https://autofixture.github.io/docs/fixture-customization/) interface and which is then applied to this test only.

refactor: Use `AutoDomainData` attribute instead of directly mocking with `NSubstitute`

---

.github/workflows/build.yml

Use "skip-label" in [apexskier/github-release-commenter](https://github.com/apexskier/github-release-commenter) to exclude dependabot PRs

refactor: skip release message for pull requests with "dependencies" label

---

Tests/Testably.Abstractions.Tests/FileSystem/Path/GetTempPathTests.cs

See https://github.com/TestableIO/System.IO.Abstractions/issues/1171

refactor: add test to ensure, that `GetTempPath` ends with a directory separator

---

Directory.Packages.props
Tests/Directory.Build.props
Tests/Helpers/Testably.Abstractions.TestHelpers/Testably.Abstractions.TestHelpers.csproj
Tests/Helpers/Testably.Abstractions.Tests.SourceGenerator/ClassGenerators/FileSystemClassGenerator.cs
Tests/Helpers/Testably.Abstractions.Tests.SourceGenerator/ClassGenerators/TimeSystemClassGenerator.cs
Tests/Testably.Abstractions.AccessControl.Tests/AccessControlHelperTests.cs
Tests/Testably.Abstractions.AccessControl.Tests/DirectoryAclExtensionsTests.cs
Tests/Testably.Abstractions.AccessControl.Tests/DirectoryInfoAclExtensionsTests.cs
Tests/Testably.Abstractions.AccessControl.Tests/ExceptionMissingFileTests.cs
Tests/Testably.Abstractions.AccessControl.Tests/ExceptionTests.cs
Tests/Testably.Abstractions.AccessControl.Tests/FileAclExtensionsTests.cs
Tests/Testably.Abstractions.AccessControl.Tests/FileInfoAclExtensionsTests.cs
Tests/Testably.Abstractions.AccessControl.Tests/FileStreamAclExtensionsTests.cs
Tests/Testably.Abstractions.AccessControl.Tests/Internal/AccessControlHelperTests.cs
Tests/Testably.Abstractions.AccessControl.Tests/TestHelpers/Usings.cs
Tests/Testably.Abstractions.Compression.Tests/Testably.Abstractions.Compression.Tests.csproj
Tests/Testably.Abstractions.Parity.Tests/ParityTests.cs
Tests/Testably.Abstractions.Parity.Tests/TestHelpers/Usings.cs
Tests/Testably.Abstractions.Testing.Tests/Testably.Abstractions.Testing.Tests.csproj
Tests/Testably.Abstractions.Tests/Testably.Abstractions.Tests.csproj

Start using [aweXpect](https://github.com/aweXpect/aweXpect) as an assertion library:
- Testably.Abstractions.AccessControl.Tests
- Testably.Abstractions.Parity.Tests

refactor: use aweXpect

---

Directory.Packages.props
Tests/Directory.Build.props
Tests/Testably.Abstractions.Compression.Tests/Internal/ExecuteTests.cs
Tests/Testably.Abstractions.Compression.Tests/Internal/ZipUtilitiesTests.cs
Tests/Testably.Abstractions.Compression.Tests/TestHelpers/Usings.cs
Tests/Testably.Abstractions.Compression.Tests/ZipArchive/ExtensionTests.cs
Tests/Testably.Abstractions.Compression.Tests/ZipArchive/Tests.cs
Tests/Testably.Abstractions.Compression.Tests/ZipArchiveEntry/ExtensionTests.cs
Tests/Testably.Abstractions.Compression.Tests/ZipArchiveEntry/Tests.cs
Tests/Testably.Abstractions.Compression.Tests/ZipArchiveFactory/Tests.cs
Tests/Testably.Abstractions.Compression.Tests/ZipFile/CreateFromDirectoryTests.cs
Tests/Testably.Abstractions.Compression.Tests/ZipFile/ExtractToDirectoryTests.cs
Tests/Testably.Abstractions.Compression.Tests/ZipFile/OpenTests.cs
Tests/Testably.Abstractions.Compression.Tests/ZipFile/Tests.cs

Use [aweXpect](https://github.com/aweXpect/aweXpect) as an assertion library for Testably.Abstractions.Compression.Tests

refactor: use aweXpect for Compression project

---

Directory.Packages.props

Revert #684, as it deactivates the generation of the unit test classes.

fix: test classes are not source generated anymore

---

Directory.Packages.props
Tests/Testably.Abstractions.Compression.Tests/ZipFile/CreateFromDirectoryTests.cs
Tests/Testably.Abstractions.Compression.Tests/ZipFile/ExtractToDirectoryTests.cs

Revert Microsoft.CodeAnalysis.CSharp to 4.11.0 as 4.12.0 does not generate tests correctly

fix: tests are not generated/executed

---

Directory.Packages.props
Source/Testably.Abstractions.Testing/FileSystem/FileVersionInfoFactoryMock.cs
Source/Testably.Abstractions.Testing/FileSystem/FileVersionInfoMock.cs
Source/Testably.Abstractions.Testing/MockFileSystem.cs
Source/Testably.Abstractions.Testing/Statistics/FileSystemStatistics.cs
Source/Testably.Abstractions.Testing/Statistics/IFileSystemStatistics.cs
Source/Testably.Abstractions/FileSystem/FileVersionInfoFactory.cs
Source/Testably.Abstractions/FileSystem/FileVersionInfoWrapper.cs
Source/Testably.Abstractions/RealFileSystem.cs
Tests/Api/Testably.Abstractions.Api.Tests/Expected/Testably.Abstractions.Testing_net6.0.txt
Tests/Api/Testably.Abstractions.Api.Tests/Expected/Testably.Abstractions.Testing_net7.0.txt
Tests/Api/Testably.Abstractions.Api.Tests/Expected/Testably.Abstractions.Testing_net8.0.txt
Tests/Api/Testably.Abstractions.Api.Tests/Expected/Testably.Abstractions.Testing_netstandard2.0.txt
Tests/Api/Testably.Abstractions.Api.Tests/Expected/Testably.Abstractions.Testing_netstandard2.1.txt
Tests/Api/Testably.Abstractions.Api.Tests/Expected/Testably.Abstractions_net6.0.txt
Tests/Api/Testably.Abstractions.Api.Tests/Expected/Testably.Abstractions_net7.0.txt
Tests/Api/Testably.Abstractions.Api.Tests/Expected/Testably.Abstractions_net8.0.txt
Tests/Api/Testably.Abstractions.Api.Tests/Expected/Testably.Abstractions_netstandard2.0.txt
Tests/Api/Testably.Abstractions.Api.Tests/Expected/Testably.Abstractions_netstandard2.1.txt
Tests/Testably.Abstractions.Parity.Tests/ParityTests.cs
Tests/Testably.Abstractions.Parity.Tests/TestHelpers/Parity.cs
Tests/Testably.Abstractions.Testing.Tests/Statistics/FileSystem/FileVersionInfoFactoryStatisticsTests.cs
Tests/Testably.Abstractions.Testing.Tests/Statistics/FileSystem/FileVersionInfoStatisticsTests.cs
Tests/Testably.Abstractions.Testing.Tests/Statistics/StatisticsTests.cs

Support for `FileVersionInfo` was added in https://github.com/TestableIO/System.IO.Abstractions/pull/1177. Add basic support for the updated interfaces.
*It is not yet possible to influence the mocked `IFileVersionInfo` in any way...*

feat: Add initial `FileVersionInfo` support

---

Pipeline/Build.CodeAnalysis.cs
Pipeline/Build.Compile.cs
Pipeline/Build.MutationTests.cs
Pipeline/Build.Pack.cs
Pipeline/Build.cs
Pipeline/Build.csproj
Pipeline/BuildExtensions.cs

When the mutation comment is updated, it adds an incorrect string:

fix: mutation comment during update

---

.github/workflows/build.yml
.github/workflows/ci.yml
Directory.Packages.props
Source/Testably.Abstractions.Testing/FileSystem/FileVersionInfoFactoryMock.cs
Source/Testably.Abstractions.Testing/FileSystem/FileVersionInfoMock.cs
Source/Testably.Abstractions.Testing/Initializer/FileVersionInfoBuilder.cs
Source/Testably.Abstractions.Testing/MockFileSystem.cs
Source/Testably.Abstractions.Testing/Storage/FileVersionInfoContainer.cs
Source/Testably.Abstractions.Testing/Storage/IStorage.cs
Source/Testably.Abstractions.Testing/Storage/InMemoryStorage.cs
Source/Testably.Abstractions/FileSystem/FileVersionInfoWrapper.cs
Tests/Api/Testably.Abstractions.Api.Tests/Expected/Testably.Abstractions.Testing_net6.0.txt
Tests/Api/Testably.Abstractions.Api.Tests/Expected/Testably.Abstractions.Testing_net7.0.txt
Tests/Api/Testably.Abstractions.Api.Tests/Expected/Testably.Abstractions.Testing_net8.0.txt
Tests/Api/Testably.Abstractions.Api.Tests/Expected/Testably.Abstractions.Testing_netstandard2.0.txt
Tests/Api/Testably.Abstractions.Api.Tests/Expected/Testably.Abstractions.Testing_netstandard2.1.txt
Tests/Testably.Abstractions.Testing.Tests/FileSystem/FileVersionInfoFactoryMockTests.cs
Tests/Testably.Abstractions.Testing.Tests/FileSystemInitializer/FileVersionInfoBuilderTests.cs
Tests/Testably.Abstractions.Testing.Tests/Statistics/FileSystem/FileVersionInfoFactoryStatisticsTests.cs
Tests/Testably.Abstractions.Testing.Tests/Statistics/FileSystem/FileVersionInfoStatisticsTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileVersionInfo/Tests.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileVersionInfoFactory/ExceptionTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileVersionInfoFactory/Tests.cs

Add a method to the `MockFileSystem` that allows setting the `IFileVersionInfo`:
```csharp
MockFileSystem fileSystem = new();
fileSystem.WithFileVersionInfo("foo.dll", b => b.SetFileVersion("2.3.4"));
fileSystem.Initialize().WithFile("foo.dll");
IFileVersionInfo fileVersionInfo = fileSystem.FileVersionInfo.GetVersionInfo("foo.dll");
fileVersionInfo.FileVersion.Should().Be("2.3.4");
```

feat: enable mocking the `IFileVersionInfo`

---

Pipeline/Build.UnitTest.cs

Unit tests against the real file or time system sometimes fail. Therefore retry a failed unit test step once in the build pipeline.

refactor: retry unit test step in build pipeline

---

Pipeline/Build.UnitTest.cs
Source/Testably.Abstractions.Testing/Helpers/ExceptionFactory.cs
Source/Testably.Abstractions.Testing/Helpers/FileSystemExtensions.cs
Source/Testably.Abstractions.Testing/Helpers/FileSystemRegistration.cs
Source/Testably.Abstractions.Testing/MockFileSystem.cs
Source/Testably.Abstractions.Testing/Storage/InMemoryContainer.cs
Source/Testably.Abstractions.Testing/Storage/InMemoryStorage.cs
Source/Testably.Abstractions.Testing/TimeProvider.cs
Tests/Directory.Build.props
Tests/Helpers/Testably.Abstractions.TestHelpers/AssertionHelpers.cs
Tests/Helpers/Testably.Abstractions.Tests.SourceGenerator/ClassGenerators/FileSystemClassGenerator.cs
Tests/Testably.Abstractions.Testing.Tests/FileSystem/DriveInfoMockTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileStreamFactory/Tests.cs
Tests/Testably.Abstractions.Tests/RandomSystem/RandomTests.cs
Tests/Testably.Abstractions.Tests/TimeSystem/DateTimeTests.cs
Tests/Testably.Abstractions.Tests/TimeSystem/TimerTests.cs

Continuing to fix the analyzer warnings (see #711)

refactor: fix analyzer warnings (3)

---

Source/Testably.Abstractions.AccessControl/Testably.Abstractions.AccessControl.csproj
Source/Testably.Abstractions.Compression/Testably.Abstractions.Compression.csproj
Source/Testably.Abstractions.Testing/Testably.Abstractions.Testing.csproj
Source/Testably.Abstractions/Testably.Abstractions.csproj

Use the `InternalsVisibleTo` property instead of the generic "AssemblyAttribute"

refactor: simplify `InternalsVisibleTo`

---

Directory.Packages.props

Use a framework-dependent version of ["System.Threading.Channels"](https://www.nuget.org/packages/System.Threading.Channels#versions-body-tab).

fix: avoid warnings about untested "System.Threading.Channels" version

---

Directory.Packages.props
Tests/Testably.Abstractions.AccessControl.Tests/AccessControlHelperTests.cs
Tests/Testably.Abstractions.AccessControl.Tests/DirectoryAclExtensionsTests.cs
Tests/Testably.Abstractions.AccessControl.Tests/DirectoryInfoAclExtensionsTests.cs
Tests/Testably.Abstractions.AccessControl.Tests/ExceptionMissingFileTests.cs
Tests/Testably.Abstractions.AccessControl.Tests/ExceptionTests.cs
Tests/Testably.Abstractions.AccessControl.Tests/FileAclExtensionsTests.cs
Tests/Testably.Abstractions.AccessControl.Tests/FileInfoAclExtensionsTests.cs
Tests/Testably.Abstractions.AccessControl.Tests/FileStreamAclExtensionsTests.cs
Tests/Testably.Abstractions.AccessControl.Tests/Internal/AccessControlHelperTests.cs
Tests/Testably.Abstractions.Compression.Tests/Internal/ExecuteTests.cs
Tests/Testably.Abstractions.Compression.Tests/Internal/ZipUtilitiesTests.cs
Tests/Testably.Abstractions.Compression.Tests/ZipArchive/ExtensionTests.cs
Tests/Testably.Abstractions.Compression.Tests/ZipArchive/Tests.cs
Tests/Testably.Abstractions.Compression.Tests/ZipArchiveEntry/ExtensionTests.cs
Tests/Testably.Abstractions.Compression.Tests/ZipArchiveEntry/Tests.cs
Tests/Testably.Abstractions.Compression.Tests/ZipArchiveFactory/Tests.cs
Tests/Testably.Abstractions.Compression.Tests/ZipFile/CreateFromDirectoryTests.cs
Tests/Testably.Abstractions.Compression.Tests/ZipFile/ExtractToDirectoryTests.cs
Tests/Testably.Abstractions.Compression.Tests/ZipFile/OpenTests.cs
Tests/Testably.Abstractions.Compression.Tests/ZipFile/Tests.cs
Tests/Testably.Abstractions.Parity.Tests/ParityTests.cs

adjust tests to breaking changes in "aweXpect"

refactor: update aweXpect

---

.github/workflows/build.yml

Allow creating pre-release nuget packages by appending e.g. "-pre.1" to the tag

fix: trigger build on tags with pre-release information

---

Directory.Packages.props
README.md

- Use v9.0.0 as package reference to Testably.Abstractions
- Update badge in README to reference the Testing package

chore: update Testably.Abstractions to v9.0.0

---

Directory.Packages.props
Tests/Testably.Abstractions.Compression.Tests/ZipFile/CreateFromDirectoryTests.cs
Tests/Testably.Abstractions.Compression.Tests/ZipFile/ExtractToDirectoryTests.cs

Use new functionality with file content `SameAs` in tests

chore: update aweXpect.Testably to v0.8.0

---

README.md

As highlighted in #762 the versioning scheme with different versions for `Testably.Abstractions` and the interface projects vs the Testing project might be confusing. Therefore include both versions as nuget badge in README.md.

docs: also include nuget badge for Testably.Abstractions

---

Tests/Api/Testably.Abstractions.Api.Tests/Testably.Abstractions.Api.Tests.csproj
Tests/Api/Testably.Abstractions.Core.Api.Tests/Testably.Abstractions.Core.Api.Tests.csproj
Tests/Directory.Build.props
Tests/Helpers/Testably.Abstractions.TestHelpers/Testably.Abstractions.TestHelpers.csproj
Tests/Settings/Testably.Abstractions.TestSettings/Testably.Abstractions.TestSettings.csproj
Tests/Testably.Abstractions.AccessControl.Tests/Testably.Abstractions.AccessControl.Tests.csproj
Tests/Testably.Abstractions.Compression.Tests/Testably.Abstractions.Compression.Tests.csproj
Tests/Testably.Abstractions.Parity.Tests/Testably.Abstractions.Parity.Tests.csproj
Tests/Testably.Abstractions.Testing.Tests/Testably.Abstractions.Testing.Tests.csproj
Tests/Testably.Abstractions.Tests/Testably.Abstractions.Tests.csproj

Consolidate NCrunch target framework in the `Directory.Build.props` file for tests.

refactor: remove NCrunch from test projects

---

Source/Testably.Abstractions.Compression/Internal/ZipUtilities.cs
Tests/Testably.Abstractions.Compression.Tests/ZipFile/CreateFromDirectoryTests.cs

Fixes #763 
The file stream used to create the zip file was not disposed correctly.

fix: zipped file remains locked after `ZipFile().CreateFromDirectory`

---

.gitignore
Source/Testably.Abstractions.Testing/Helpers/Execute.WindowsPath.cs
Testably.Abstractions.sln.DotSettings
Tests/Testably.Abstractions.Tests/FileSystem/Directory/ExistsTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/DirectoryInfo/ExistsTests.cs

See https://github.com/TestableIO/System.IO.Abstractions/issues/1244

fix: directory with forward slash exists on windows

---

Source/Testably.Abstractions.Testing/FileSystem/FileStreamMock.cs
Tests/Testably.Abstractions.Testing.Tests/TimeSystem/TimerMockTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileStream/ParallelTests.cs

This PR enhances parallel write support for `IFileStream` by ensuring only the modified byte ranges are flushed per stream, and adds tests to validate this behavior.
- Added parallel write and flush behavior tests covering overlapping writes, differing lengths, and empty writes.
- Updated `FileStreamMock` to track minimum and maximum write positions and flush only the modified segments.

fix: parallel access to `IFileStream`

---

Source/Testably.Abstractions.Testing/MockFileSystem.cs
Tests/Api/Testably.Abstractions.Api.Tests/Expected/Testably.Abstractions.Testing_net6.0.txt
Tests/Api/Testably.Abstractions.Api.Tests/Expected/Testably.Abstractions.Testing_net8.0.txt
Tests/Api/Testably.Abstractions.Api.Tests/Expected/Testably.Abstractions.Testing_net9.0.txt
Tests/Api/Testably.Abstractions.Api.Tests/Expected/Testably.Abstractions.Testing_netstandard2.0.txt
Tests/Api/Testably.Abstractions.Api.Tests/Expected/Testably.Abstractions.Testing_netstandard2.1.txt
Tests/Testably.Abstractions.Testing.Tests/MockFileSystemInitializationTests.cs

This PR adds the ability to configure a custom `ITimeSystem` when initializing a `MockFileSystem`, enhancing the testing capabilities by allowing developers to control time behavior in their tests.
- Adds a new `UseTimeSystem()` method to `MockFileSystemOptions` for configuring custom time systems
- Updates the `MockFileSystem` constructor to use the provided time system instead of always defaulting to current time

feat: allow setting the used `ITimeSystem`

---

.github/workflows/build.yml

This PR fixes the CI/CD pipeline by ensuring NuGet.exe is properly installed before attempting to push packages. The changes address a missing dependency issue that was previously masked by using macOS runners which have NuGet pre-installed.
- Switches the package push jobs from `macos-latest` to `ubuntu-latest` runners
- Adds explicit NuGet.exe installation step using the official [setup-nuget](https://github.com/marketplace/actions/setup-nuget-exe-for-use-with-actions) action
- Ensures consistent tooling across both core and regular package push workflows

fix: install nuget.exe before pushing packages

---

.github/workflows/build.yml

This PR modernizes the NuGet package publishing process by replacing the legacy `nuget.exe` tool with the built-in `dotnet nuget` command. This change follows best practices recommended in [Meziantou's blog]((https://www.meziantou.net/publishing-a-nuget-package-following-best-practices-using-github.htm)) for more reliable and streamlined package publishing.
Key changes:
- Replaces `nuget/setup-nuget@v2` action with `actions/setup-dotnet@v4`
- Updates push commands from `nuget push` to `dotnet nuget push` with updated parameter syntax

fix: use `dotnet nuget` to push packages

---

Directory.Packages.props
Examples/.idea/.idea.Examples/.idea/vcs.xml
Examples/Examples.sln
Examples/README.md
Examples/UnixFileMode/README.md
Examples/UnixFileMode/UnixFileMode.Tests/DefaultUnixFileModeStrategyTests.cs
Examples/UnixFileMode/UnixFileMode.Tests/UnixFileMode.Tests.csproj
Examples/UnixFileMode/UnixFileMode/DefaultUnixFileModeStrategy.cs
Examples/UnixFileMode/UnixFileMode/UnixFileMode.csproj

This PR adds a comprehensive example demonstrating how to work with `UnixFileMode` in the `MockFileSystem`. The example includes a complete implementation of a Unix file mode strategy that simulates user and group permissions for testing scenarios.
This example highlights how to simulate working with the [`UnixFileMode`](https://learn.microsoft.com/en-us/dotnet/api/system.io.unixfilemode) in the `MockFileSystem`.
The `DefaultUnixFileModeStrategy` simulates the user and group and stores this information alongside the file/directory in the `OnSetUnixFileMode` method.
Later in the `IsAccessGranted` method you can access the stored data from the `IFileSystemExtensibility` and act accordingly to read or write requests in the `MockFileSystem`.
Read access is granted when
- When the unix file …

docs: add example for working with `UnixFileMode`

---

Source/Testably.Abstractions.Testing/Helpers/ExceptionFactory.cs
Source/Testably.Abstractions.Testing/Storage/IStorageContainer.cs
Source/Testably.Abstractions.Testing/Storage/InMemoryContainer.cs
Source/Testably.Abstractions.Testing/Storage/InMemoryStorage.cs
Source/Testably.Abstractions.Testing/Storage/NullContainer.cs
Tests/Testably.Abstractions.Testing.Tests/MockFileSystemTests.cs
Tests/Testably.Abstractions.Testing.Tests/TestHelpers/LockableContainer.cs
Tests/Testably.Abstractions.Tests/FileSystem/Directory/CreateDirectoryTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/DirectoryInfo/CreateTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/File/WriteAllTextTests.cs

This PR fixes an issue where ACL-denied access operations were throwing `IOException` instead of the correct `UnauthorizedAccessException` on Windows. The change ensures proper exception handling when trying to create directories or write files in directories that are denied access by Windows ACL.
- Fixes the exception type thrown when ACL denies access from `IOException` to `UnauthorizedAccessException`
- Updates the storage container interface to pass location context for better error reporting
---
- *Fixes #829*

fix: throw correct exception when ACL denies access

---

Source/Testably.Abstractions.Testing/TimeProvider.cs
Source/Testably.Abstractions.Testing/TimeSystem/TimeProviderMock.cs
Tests/Testably.Abstractions.Testing.Tests/MockTimeSystemTests.cs
Tests/Testably.Abstractions.Testing.Tests/TimeProviderTests.cs
Tests/Testably.Abstractions.Testing.Tests/TimeSystem/NotificationHandlerTests.cs

The difference between `DateTime.Now` And `DateTime.UtcNow` should be the offset from the local time zone to UTC. Before this change, `MockTimeSystem` would produce a difference double that size when initialized with a `DateTime` having `Kind` `DateTimeKind.Unspecified`.
The `MockTimeSystem` delegates to a `MockDateTime` wrapped around a `TimeProviderMock`. The `TimeProviderMock` would yield a `DateTime` with `Kind` `DateTimeKind.Unspecified` to the `MockDateTime`, which would then apply `ToLocalTime()` for `Now` or `ToUniversalTime` for `UtcNow`. When applied to a `DateTime` with `Kind` `DateTimeKind.Unspecified`, `ToLocalTime` assumes that the value is in UTC, but `ToUniversalTime` assumes that it is Local. This discrepancy results in the doubling of the expected difference. …

fix: MockTimeProvider constructor treats "now" having DateTimeKind.Unspecified as if it had DateTimeKind.Local

---

Directory.Packages.props
Source/Testably.Abstractions.Testing/FileSystem/FileSystemInfoMock.cs
Source/Testably.Abstractions.Testing/Helpers/ExceptionFactory.cs
Source/Testably.Abstractions.Testing/Storage/InMemoryContainer.cs
Source/Testably.Abstractions.Testing/Storage/InMemoryStorage.cs
Tests/Testably.Abstractions.Tests/FileSystem/DirectoryInfo/ResolveLinkTargetTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/FileInfo/ResolveLinkTargetTests.cs

fix(FileSystem): When creating chained sym links of different types MockFileSystem in windows doesn't throw

---

Source/Testably.Abstractions.Testing/FileSystem/FileMock.cs
Tests/Testably.Abstractions.Tests/FileSystem/File/AppendAllLinesAsyncTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/File/AppendAllLinesTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/File/AppendAllTextAsyncTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/File/AppendAllTextTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/File/WriteAllLinesAsyncTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/File/WriteAllLinesTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/File/WriteAllTextAsyncTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/File/WriteAllTextTests.cs

This PR fixes the default encoding behavior in file write and append methods to use UTF-8 without BOM (byte order mark) instead of the system default encoding when no encoding is explicitly specified. This improves cross-platform compatibility.
- Modified file write/append methods to use UTF-8 encoding without preamble as default
- Consolidated encoding logic into a single `WriteText` helper method
- Added comprehensive tests to verify UTF-8 encoding behavior across all affected methods
---
- *Fixes #843*

fix: use UTF8 encoding without preamble as default

---

Source/Testably.Abstractions.Testing/Storage/InMemoryLocation.cs
Tests/Testably.Abstractions.Tests/FileSystem/DirectoryInfo/Tests.cs

This PR fixes a bug in the `DirectoryInfo.Parent` property when the directory path contains a trailing directory separator. The issue was that the parent directory calculation incorrectly included the trailing separator, leading to wrong parent resolution.
- Fixed the `GetParent()` method in `InMemoryLocation` to trim trailing directory separators before calculating the parent path
- Added a test case to verify the correct parent is returned when a directory path has a trailing separator
---
- *Fixes #842*

fix: return correct `Parent` of `DirectoryInfo` with trailing directory separator

---

Source/Testably.Abstractions.Testing/FileSystem/DirectoryMock.cs
Source/Testably.Abstractions.Testing/Helpers/PathHelper.cs
Source/Testably.Abstractions.Testing/Storage/InMemoryStorage.cs
Tests/Testably.Abstractions.Tests/FileSystem/Directory/CreateDirectoryTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/Directory/EnumerateDirectoriesTests.cs
Tests/Testably.Abstractions.Tests/FileSystem/Directory/GetDirectoriesTests.cs

This PR fixes the `Directory.GetDirectories` method to trim trailing slashes from directory paths in the returned results. This ensures consistent behavior where directory paths returned by enumeration methods don't include trailing directory separators.
- Adds helper method `TrimTrailingDirectorySeparator` for consistent path normalization
- Updates directory enumeration logic to remove trailing slashes from results
- Includes comprehensive test coverage for both `GetDirectories` and `EnumerateDirectories` methods
---
- *Fixes #850*

fix: trim trailing slash in `Directory.GetDirectories`

---

.github/workflows/build.yml

This PR adds logic to the build pipeline to differentiate between stable releases and pre-releases, ensuring that GitHub release creation and issue commenting only occur for stable releases (matching the pattern `v[0-9]+.[0-9]+.[0-9]+$` without additional suffixes).
- Added pre-release detection steps that check if tags match the stable release pattern
- Conditionally execute GitHub release creation only for stable releases
- Conditionally execute issue/PR commenting only for stable releases

feat: consider pre-releases in build pipeline

---

Docs/AccessControl.md
Docs/Compression.md
Docs/Interface.md
Docs/Testing.md

This PR removes the mutation testing badge from all documentation files in the project. The change removes references to the Stryker mutation testing dashboard badge that was previously displayed alongside other project status badges like build status, quality gate, and code coverage.

docs: remove mutation testing badge

---

.github/workflows/ci.yml

This PR modifies the static code analysis workflow to run on all pull requests from the same repository while excluding dependabot PRs, rather than only running for a specific user.
- Updates the workflow condition to exclude dependabot and external repository PRs
- Removes user-specific restriction on static code analysis execution

fix: run static code analysis in CI build only from this repo

---

Source/Testably.Abstractions.Testing/FileSystem/FileSystemWatcherMock.cs

This PR refactors the `FileSystemWatcherMock` class to optimize performance by conditionally using reflection only when simulating non-native operating systems, rather than always using reflection for path manipulation.
- Conditional reflection usage based on simulation mode to improve performance in native scenarios
- Updated constructor parameters to use the `Path` property instead of local variables

refactor: only use reflection in `FileSystemWatcherMock` when simulating other OS

---

CONTRIBUTING.md

This PR removes outdated versioning information from the CONTRIBUTING.md file that described the use of MinVer for versioning and release branch naming conventions.
- Removes the entire "Versioning" section that documented MinVer usage and release procedures
- Eliminates outdated information about release branch naming conventions

docs: Remove outdated versioning information
